#!/usr/bin/env python3
"""Generate tests/dotnet/MathBits.cs: every Math / MathF function over a deterministic spread of inputs
(zeros, infinities, NaN, subnormals, huge and tiny values, and a pseudo-random sweep), hashing the raw
result bits. DNA's output must equal Mono's, and the real .NET runtime's, line for line: the claim is
bit-for-bit agreement, not "close". Regenerate with: python3 tests/gen_mathbits.py
"""
import os
F1 = ["Sin","Cos","Tan","Asin","Acos","Atan","Sinh","Cosh","Tanh","Sqrt","Exp","Log","Log10","Log2","Floor","Ceiling","Round","Truncate","Cbrt","Abs"]
F2 = ["Atan2","Pow","IEEERemainder","Max","Min"]
o=[]; w=o.append
w("// GENERATED by tests/gen_mathbits.py -- do not edit.")
w("using System;")
w("class Program {")
w("    static uint s = 12345;")
w("    static uint Rnd() { s = s * 1664525u + 1013904223u; return s; }")
w("    static unsafe uint Bits(float f) { if (f != f) return 0x7FC00000u; return *(uint*)&f; }")
w("    static unsafe ulong Bits(double d) { if (d != d) return 0x7FF8000000000000UL; return *(ulong*)&d; }")
w("    static uint Mix(uint h, uint v) { return (h ^ v) * 16777619u; }")
w("    static uint Mix(uint h, ulong v) { return Mix(Mix(h, (uint)v), (uint)(v >> 32)); }")
w("    static unsafe float F(uint b) { return *(float*)&b; }")
w("    static unsafe double D(ulong b) { return *(double*)&b; }")
w("    static float[] fs; static double[] ds;")
w("    static unsafe void Init() {")
w("        int n = 600; fs = new float[n + 40]; ds = new double[n + 40]; int k = 0;")
w("        float[] sf = new float[] { 0f, -0f, 1f, -1f, 0.5f, -0.5f, 2f, -2f, 3.5f, -3.5f, 2.5f, -2.5f, 1.5f, -1.5f, 0.1f, 100f, -100f, 1e10f, -1e10f, 1e-10f, 3.14159265f, 1.5707964f, 6.2831855f, 1e30f, -1e30f, 1e-40f, -1e-40f, float.MaxValue, float.MinValue, float.Epsilon, float.NaN, float.PositiveInfinity, float.NegativeInfinity, 8388608f, 16777216f, 0.99999994f, 1.0000001f, 123456.789f, -0.0001f, 7f };")
w("        for (int i = 0; i < sf.Length; i++) { fs[k] = sf[i]; ds[k] = (double)sf[i]; k++; }")
w("        double[] sd = new double[] { 1e300, -1e300, 1e-300, 2.2250738585072014e-308, 4.9e-324, 0.1, 1e15, 1e16, 4503599627370496.0, 4503599627370497.0 };")
w("        for (int i = 0; i < sd.Length && k < ds.Length; i++) { ds[k] = sd[i]; fs[k] = (float)sd[i]; k++; }")
w("        for (; k < n + 40; k++) {")
w("            uint a = Rnd(); uint b = Rnd();")
w("            float f = F(a); if (f != f || float.IsInfinity(f)) f = (float)(a % 2000) / 8f - 100f;")
w("            int mode = (int)(b % 4);")
w("            if (mode == 1) f = (float)((a % 20001) - 10000) / 100f;")
w("            else if (mode == 2) f = (float)((a % 2001) - 1000) / 1000f;")
w("            else if (mode == 3) f = (float)((a % 400) - 200) + 0.5f;")
w("            fs[k] = f; ds[k] = (double)f * 1.0000001 + 0.0000003;")
w("        }")
w("    }")
w("    static void Main() {")
w("        Init();")
for t,arr,bits,cast in (("MathF","fs","Bits","float"),("Math","ds","Bits","double")):
    for n in F1:
        if t=="MathF" and False: pass
        w("        { uint h = 2166136261u; for (int i = 0; i < %s.Length; i++) h = Mix(h, %s(%s.%s(%s[i]))); Console.WriteLine(\"%s.%s \" + h); }"%(arr,bits,t,n,arr,t,n))
    for n in F2:
        w("        { uint h = 2166136261u; for (int i = 0; i < %s.Length; i++) for (int j = 0; j < %s.Length; j += 7) h = Mix(h, %s(%s.%s(%s[i], %s[j]))); Console.WriteLine(\"%s.%s \" + h); }"%(arr,arr,bits,t,n,arr,arr,t,n))
# Sign, Clamp, constants
w('        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) { if (fs[i] != fs[i]) continue; h = Mix(h, (uint)MathF.Sign(fs[i])); h = Mix(h, (uint)Math.Sign(ds[i])); } Console.WriteLine("Sign " + h); }')
w('        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 11) { float lo = fs[i], hi = fs[j]; if (lo != lo || hi != hi || lo > hi) continue; for (int k = 0; k < fs.Length; k += 13) { float v = fs[k]; h = Mix(h, Bits(Math.Clamp(v, lo, hi))); } } Console.WriteLine("Clamp float " + h); }')
w('        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 11) { double lo = ds[i], hi = ds[j]; if (lo != lo || hi != hi || lo > hi) continue; for (int k = 0; k < ds.Length; k += 13) { double v = ds[k]; h = Mix(h, Bits(Math.Clamp(v, lo, hi))); } } Console.WriteLine("Clamp double " + h); }')
w('        { uint h = 2166136261u; for (int a = -40; a <= 40; a += 3) for (int b = -40; b <= 40; b += 5) for (int c = -40; c <= 40; c += 4) { if (a > b) continue; h = Mix(h, (uint)Math.Clamp(c, a, b)); h = Mix(h, (uint)Math.Clamp((long)c, (long)a, (long)b)); h = Mix(h, (uint)Math.Clamp((byte)(c + 50), (byte)(a + 50), (byte)(b + 50))); } Console.WriteLine("Clamp int " + h); }')
w('        bool thrown = false; try { Math.Clamp(1, 5, 2); } catch (ArgumentException) { thrown = true; } Console.WriteLine("Clamp min>max throws " + thrown);')
w('        Console.WriteLine("consts " + Bits(MathF.PI) + " " + Bits(MathF.E) + " " + Bits(MathF.Tau) + " " + Bits(Math.PI) + " " + Bits(Math.E));')
w("    }")
w("}")
path=os.path.join(os.path.dirname(os.path.abspath(__file__)),"dotnet","MathBits.cs")
open(path,"w").write("\n".join(o)+"\n"); print("wrote",path)
