#!/usr/bin/env python3
"""Generate tests/dotnet/ArithmeticMatrix.cs: every binary/unary operator on the numeric types at
boundary values, including the cases that throw (division by zero, int.MinValue / -1). One line
per case; the test requires DNA's stdout to equal Mono's. Regenerate with:
    python3 tests/gen_arithmetic.py
"""
import os

INTS = [("int", -2**31, 2**31 - 1, "long"), ("uint", 0, 2**32 - 1, "long"),
        ("long", -2**63, 2**63 - 1, "long"), ("ulong", 0, 2**64 - 1, "ulong")]
FLTS = ["float", "double"]
SMALL = [("sbyte", -128, 127), ("byte", 0, 255), ("short", -32768, 32767), ("ushort", 0, 65535)]
SHIFTS = [0, 1, 7, 8, 15, 16, 31, 32, 33, 63, 64, 65, -1]
FVALS = ["0.0", "-0.0", "1.0", "-1.0", "0.5", "-0.5", "2.0", "3.0", "-3.0", "7.5", "-7.5", "1024.25",
         "-1024.25", "100000.0", "1.0e10", "-1.0e10", "9007199254740992.0", "1.0e30", "-1.0e30",
         "double.NaN", "double.PositiveInfinity", "double.NegativeInfinity"]


def lit(t, v):
    if t == "ulong": return "%dUL" % v
    if t == "uint": return "%dU" % v
    if t == "long": return "(%dL)" % v if v > -2**63 else "long.MinValue"
    if t == "int": return "(%d)" % v if v > -2**31 else "int.MinValue"
    return "((%s)%d)" % (t, v)


def ivals(mn, mx):
    s = {0, 1, 2, 3, 7, 10, 100, mn, mx, mn + 1, mx - 1, mx // 2, mx // 2 + 1, 255, 256, 65535, 65536, 2**31 - 1, 2**31, 2**32 - 1}
    if mn < 0:
        s |= {-1, -2, -3, -7, -10, -100, mn // 2, -255, -256, -2**31}
    return sorted(v for v in s if mn <= v <= mx)


def main():
    o = []
    w = o.append
    w("// GENERATED by tests/gen_arithmetic.py -- do not edit.")
    w("using System;")
    w("")
    w("class Program {")
    w("    static string R(long v) { return v.ToString(); }")
    w("    static string R(ulong v) { return v.ToString(); }")
    w("    static string F(double r) {")
    w("        if (double.IsNaN(r)) return \"NaN\";")
    w("        if (double.IsPositiveInfinity(r)) return \"+Inf\";")
    w("        if (double.IsNegativeInfinity(r)) return \"-Inf\";")
    w("        double s = r * 1024.0;")
    w("        if (s > 9.0e18 || s < -9.0e18) return r > 0 ? \"+BIG\" : \"-BIG\";")
    w("        return R((long)s) + (r < 0 || (r == 0 && 1.0 / r < 0) ? \"n\" : \"p\");")
    w("    }")
    w("    static string B(bool b) { return b ? \"1\" : \"0\"; }")
    calls = []
    tid = 0

    def emit(tag, expr, kind, cast):
        # kind: 'i' integer result (print via R), 'f' float result (via F), 'b' bool
        if kind == "i":
            body = "R((%s)(%s))" % (cast, expr)
        elif kind == "f":
            body = "F((double)(%s))" % expr
        else:
            body = "B(%s)" % expr
        w("            try { Console.WriteLine(\"%s.\" + i + \".\" + j + \"=\" + %s); }" % (tag, body))
        w("            catch (Exception e) { Console.WriteLine(\"%s.\" + i + \".\" + j + \"=!\" + e.GetType().Name); }" % tag)

    for t, mn, mx, cast in INTS:
        vs = ivals(mn, mx)
        w("    static void T%d_%s() {" % (tid, t))
        w("        %s[] vs = new %s[] { %s };" % (t, t, ", ".join(lit(t, v) for v in vs)))
        w("        int[] sh = new int[] { %s };" % ", ".join(str(x) for x in SHIFTS))
        w("        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {")
        w("            %s a = vs[i]; %s b = vs[j];" % (t, t))
        k = 0
        for op, sym in [("add", "+"), ("sub", "-"), ("mul", "*"), ("div", "/"), ("rem", "%"),
                        ("and", "&"), ("or", "|"), ("xor", "^")]:
            # operands of int/uint promote: int op int -> int, uint op uint -> uint; both fit in `cast`
            emit("%d.%d" % (tid, k), "unchecked(a %s b)" % sym, "i", cast); k += 1
        for op, sym in [("eq", "=="), ("ne", "!="), ("lt", "<"), ("gt", ">"), ("le", "<="), ("ge", ">=")]:
            emit("%d.%d" % (tid, k), "a %s b" % sym, "b", cast); k += 1
        w("        }")
        w("        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < sh.Length; j++) {")
        w("            %s a = vs[i]; int n = sh[j];" % t)
        k2 = 100
        for sym in ("<<", ">>"):
            emit("%d.%d" % (tid, k2), "a %s n" % sym, "i", cast); k2 += 1
        emit("%d.%d" % (tid, k2), "~a", "i", cast); k2 += 1
        if t in ("int", "long"):
            emit("%d.%d" % (tid, k2), "unchecked(-a)", "i", cast); k2 += 1
        w("        }")
        w("    }")
        calls.append("T%d_%s();" % (tid, t)); tid += 1

    for t in FLTS:
        w("    static void T%d_%s() {" % (tid, t))
        vals = [("(%s)(%s)" % (t, v)) if t == "float" else v for v in FVALS]
        w("        %s[] vs = new %s[] { %s };" % (t, t, ", ".join(vals)))
        w("        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {")
        w("            %s a = vs[i]; %s b = vs[j];" % (t, t))
        k = 0
        for sym in ("+", "-", "*", "/", "%"):
            emit("%d.%d" % (tid, k), "a %s b" % sym, "f", "long"); k += 1
        for sym in ("==", "!=", "<", ">", "<=", ">="):
            emit("%d.%d" % (tid, k), "a %s b" % sym, "b", "long"); k += 1
        emit("%d.%d" % (tid, k), "-a", "f", "long"); k += 1
        w("        }")
        w("    }")
        calls.append("T%d_%s();" % (tid, t)); tid += 1

    # small types: promotion to int, compound assignment narrowing back, ++/--
    for t, mn, mx in SMALL:
        vs = ivals(mn, mx)
        w("    static void T%d_%s() {" % (tid, t))
        w("        %s[] vs = new %s[] { %s };" % (t, t, ", ".join(lit(t, v) for v in vs)))
        w("        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {")
        w("            %s a = vs[i]; %s b = vs[j];" % (t, t))
        k = 0
        for sym in ("+", "-", "*", "/", "%", "&", "|", "^"):
            emit("%d.%d" % (tid, k), "unchecked(a %s b)" % sym, "i", "long"); k += 1
            emit("%d.%d" % (tid, k), "unchecked((%s)(a %s b))" % (t, sym), "i", "long"); k += 1
            w("            try { %s c = a; c = unchecked((%s)(c %s b)); Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, t, sym, tid, k))
            w("            catch (Exception e) { Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=!\" + e.GetType().Name); }" % (tid, k)); k += 1
        for sym in ("<", ">", "==", "<=", ">=", "!="):
            emit("%d.%d" % (tid, k), "a %s b" % sym, "b", "long"); k += 1
        w("            { %s c = a; c++; Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, tid, k)); k += 1
        w("            { %s c = a; c--; Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, tid, k)); k += 1
        w("            { %s c = a; c = (%s)(c << (j & 15)); Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, t, tid, k)); k += 1
        w("            { %s c = a; c = (%s)(c >> (j & 15)); Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, t, tid, k)); k += 1
        w("            { %s c = a; unchecked { c += b; } Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, tid, k)); k += 1
        w("            { %s c = a; unchecked { c *= b; } Console.WriteLine(\"%d.%d.\" + i + \".\" + j + \"=\" + R((long)c)); }" % (t, tid, k)); k += 1
        w("        }")
        w("    }")
        calls.append("T%d_%s();" % (tid, t)); tid += 1

    w("    public static int Main() {")
    for c in calls: w("        " + c)
    w("        return 0;")
    w("    }")
    w("}")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dotnet", "ArithmeticMatrix.cs")
    open(path, "w").write("\n".join(o) + "\n")
    print("wrote", path, "(%d lines)" % len(o))


if __name__ == "__main__":
    main()
