#!/usr/bin/env python3
"""Generate tests/dotnet/UncheckedConversions.cs: every source x destination pair of the
numeric types through a plain (unchecked) cast, at boundary values, printed one case per line.
The test compares DNA's output with Mono's. Float->integer casts are only generated for values
whose truncation fits the destination, since out-of-range ones are undefined behaviour in C and
differ between runtimes. Regenerate with:  python3 tests/gen_unchecked_conversions.py
"""
import math, os, struct

INT = [("sbyte", -128, 127), ("byte", 0, 255), ("short", -32768, 32767), ("ushort", 0, 65535),
       ("int", -2**31, 2**31 - 1), ("uint", 0, 2**32 - 1), ("long", -2**63, 2**63 - 1),
       ("ulong", 0, 2**64 - 1)]
FLT = ["float", "double"]
FLOAT_VALUES = ["0.0", "0.5", "-0.5", "1.0", "-1.0", "2.9", "-2.9", "127.0", "127.9", "128.0",
                "-128.0", "-128.9", "255.0", "255.5", "256.0", "32767.9", "-32768.0", "65535.5",
                "65536.0", "2147483647.0", "-2147483648.0", "4294967295.0", "4294967296.0",
                "1099511627776.5", "-1099511627776.5", "9007199254740992.0", "4611686018427387904.0",
                "-4611686018427387904.0", "9223372036854774784.0", "-9223372036854775808.0",
                "1.0e19", "1.8e19"]
F32 = lambda x: struct.unpack("f", struct.pack("f", x))[0]


def lit(t, v):
    if t == "ulong": return "%dUL" % v
    if t == "uint": return "%dU" % v
    if t == "long": return "(%dL)" % v if v > -2**63 else "long.MinValue"
    if t == "int": return "(%d)" % v if v > -2**31 else "int.MinValue"
    return "((%s)%d)" % (t, v)


def int_values(smin, smax):
    vals = {0, 1, -1, 2, smin, smax, smin + 1, smax - 1, 100, -100}
    for _, dmin, dmax in INT:
        for b in (dmin, dmax):
            for d in (-1, 0, 1):
                vals.add(b + d)
    return sorted(v for v in vals if smin <= v <= smax)


def main():
    o = []
    w = o.append
    w("// GENERATED by tests/gen_unchecked_conversions.py -- do not edit.")
    w("using System;")
    w("")
    w("class Program {")
    w("    static string R(long v) { return v.ToString(); }")
    w("    static string R(ulong v) { return v.ToString(); }")
    w("    static string B(double v) { return v > 0 ? \"+BIG\" : \"-BIG\"; }")
    calls = []
    srcs = INT + [(f, None, None) for f in FLT]
    for si, (sname, smin, smax) in enumerate(srcs):
        isf = sname in FLT
        w("    static void S%d_%s() {" % (si, sname))
        # values with (python value, literal)
        if isf:
            vals = []
            for v in FLOAT_VALUES:
                for sign in ("", "-") if v not in ("0.0",) and not v.startswith("-") else ("",):
                    lit_ = sign + v
                    vals.append(float(lit_))
            lits = []
            seen = set()
            for v in vals:
                key = repr(v)
                if key in seen: continue
                seen.add(key)
                lits.append(("(%s)(%r)" % (sname, v)) if sname == "float" else repr(v))
            pyvals = [float(l.strip("()").replace("float)", "").replace("(", "")) if False else None for l in lits]
            real = []
            seen = set()
            for v in vals:
                if repr(v) in seen: continue
                seen.add(repr(v)); real.append(F32(v) if sname == "float" else v)
            w("        %s[] vs = new %s[] { %s };" % (sname, sname, ", ".join(lits)))
        else:
            ivals = int_values(smin, smax)
            real = ivals
            w("        %s[] vs = new %s[] { %s };" % (sname, sname, ", ".join(lit(sname, v) for v in ivals)))
        w("        for (int n = 0; n < vs.Length; n++) {")
        w("            %s v = vs[n];" % sname)
        for di, (dname, dmin, dmax) in enumerate(INT):
            cast = "ulong" if dname == "ulong" else "long"
            if isf:
                # only indices whose truncated value fits the destination
                ok = [i for i, x in enumerate(real) if math.isfinite(x) and dmin <= math.trunc(x) <= dmax]
                if len(ok) == 0: continue
                cond = " || ".join("n == %d" % i for i in ok)
                w("            if (%s) Console.WriteLine(\"%d.%d.\" + n + \"=\" + R((%s)unchecked((%s)v)));" % (cond, si, di, cast, dname))
            else:
                w("            Console.WriteLine(\"%d.%d.\" + n + \"=\" + R((%s)unchecked((%s)v)));" % (si, di, cast, dname))
        for fi, fname in enumerate(FLT):
            di = len(INT) + fi
            # print (long)r when the converted value is representable in long, else its sign
            w("            { %s r = unchecked((%s)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine(\"%d.%d.\" + n + \"=\" + R((long)r)); else Console.WriteLine(\"%d.%d.\" + n + \"=\" + B(r)); }" % (fname, fname, si, di, si, di))
        w("        }")
        w("    }")
        calls.append("S%d_%s();" % (si, sname))
    w("    public static int Main() {")
    for c in calls: w("        " + c)
    w("        return 0;")
    w("    }")
    w("}")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dotnet", "UncheckedConversions.cs")
    open(path, "w").write("\n".join(o) + "\n")
    print("wrote", path, "(%d lines)" % len(o))

if __name__ == "__main__":
    main()
