#!/usr/bin/env python3
"""Generate tests/dotnet/CheckedConversions.cs.

Every source x destination pair of integer/float types, each at its boundary values, through
`checked((dst)v)`. The program prints one line per case ("<src>.<dst>.<n>=<result>|OVF"); the
test compares DNA's output with Mono's, line for line, so nothing is hand-written.
Regenerate with:  python3 tests/gen_checked_conversions.py
"""
import os

# (name, C# type, python min, python max, is_float)
SRC = [("sbyte", -128, 127), ("byte", 0, 255), ("short", -32768, 32767), ("ushort", 0, 65535),
       ("int", -2**31, 2**31 - 1), ("uint", 0, 2**32 - 1), ("long", -2**63, 2**63 - 1),
       ("ulong", 0, 2**64 - 1), ("float", None, None), ("double", None, None)]
DST = [("sbyte", -128, 127), ("byte", 0, 255), ("short", -32768, 32767), ("ushort", 0, 65535),
       ("int", -2**31, 2**31 - 1), ("uint", 0, 2**32 - 1), ("long", -2**63, 2**63 - 1),
       ("ulong", 0, 2**64 - 1)]


def lit(t, v):
    if t == "ulong": return "%dUL" % v
    if t == "uint": return "%dU" % v
    if t == "long": return "(%dL)" % v if v > -2**63 else "long.MinValue"
    if t == "int": return "(%d)" % v if v > -2**31 else "int.MinValue"
    return "((%s)%d)" % (t, v)


def int_values(smin, smax):
    vals = {0, 1, -1, smin, smax, smin + 1, smax - 1}
    for _, dmin, dmax in DST:
        for b in (dmin, dmax):
            for d in (-1, 0, 1):
                vals.add(b + d)
    return sorted(v for v in vals if smin <= v <= smax)


FLOAT_VALUES = ["0.0", "-0.0", "0.5", "-0.5", "1.0", "-1.0", "2.9", "-2.9", "127.0", "127.9", "128.0",
                "-128.0", "-128.9", "-129.0", "255.0", "255.5", "256.0", "32767.9", "32768.0",
                "-32768.0", "-32769.0", "65535.5", "65536.0", "2147483647.0", "2147483648.0",
                "-2147483648.0", "-2147483649.0", "4294967295.0", "4294967296.0",
                "9223372036854775807.0", "9223372036854775808.0", "-9223372036854775808.0",
                "-9223372036854777856.0", "18446744073709551615.0", "18446744073709551616.0", "1e30",
                "-1e30", "float.NaN", "float.PositiveInfinity", "float.NegativeInfinity"]


def main():
    out = []
    w = out.append
    w("// GENERATED by tests/gen_checked_conversions.py -- do not edit.")
    w("using System;")
    w("")
    w("class Program {")
    w("    static string R(long v) { return v.ToString(); }")
    w("    static string R(ulong v) { return v.ToString(); }")
    calls = []
    for si, (sname, smin, smax) in enumerate(SRC):
        isf = sname in ("float", "double")
        if isf:
            vals = [(v if sname == "double" else "(float)(%s)" % v.replace("float.", "float.")) for v in FLOAT_VALUES]
            vals = ["(double)(%s)" % v if sname == "double" and v.startswith("float.") else v for v in vals]
            if sname == "float":
                vals = [("(float)" + v) if not v.startswith("float.") else v for v in FLOAT_VALUES]
            else:
                vals = [(v if not v.startswith("float.") else "(double)" + v) for v in FLOAT_VALUES]
        else:
            vals = [lit(sname, v) for v in int_values(smin, smax)]
        w("    static void S%d_%s(int si) {" % (si, sname))
        w("        %s[] vs = new %s[] { %s };" % (sname, sname, ", ".join(vals)))
        w("        for (int n = 0; n < vs.Length; n++) {")
        w("            %s v = vs[n];" % sname)
        for di, (dname, _, _) in enumerate(DST):
            cast = "ulong" if dname == "ulong" else "long"
            w("            try { Console.WriteLine(\"%d.%d.\" + n + \"=\" + R((%s)checked((%s)v))); }" % (si, di, cast, dname))
            w("            catch (OverflowException) { Console.WriteLine(\"%d.%d.\" + n + \"=OVF\"); }" % (si, di))
        w("        }")
        w("    }")
        calls.append("S%d_%s(%d);" % (si, sname, si))
    w("    public static int Main() {")
    for c in calls:
        w("        " + c)
    w("        return 0;")
    w("    }")
    w("}")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dotnet", "CheckedConversions.cs")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote", path, "(%d lines)" % len(out))


if __name__ == "__main__":
    main()
