// GENERATED by tests/gen_arithmetic.py -- do not edit.
using System;

class Program {
    static string R(long v) { return v.ToString(); }
    static string R(ulong v) { return v.ToString(); }
    static string F(double r) {
        if (double.IsNaN(r)) return "NaN";
        if (double.IsPositiveInfinity(r)) return "+Inf";
        if (double.IsNegativeInfinity(r)) return "-Inf";
        double s = r * 1024.0;
        if (s > 9.0e18 || s < -9.0e18) return r > 0 ? "+BIG" : "-BIG";
        return R((long)s) + (r < 0 || (r == 0 && 1.0 / r < 0) ? "n" : "p");
    }
    static string B(bool b) { return b ? "1" : "0"; }
    static void T0_int() {
        int[] vs = new int[] { int.MinValue, (-2147483647), (-1073741824), (-256), (-255), (-100), (-10), (-7), (-3), (-2), (-1), (0), (1), (2), (3), (7), (10), (100), (255), (256), (65535), (65536), (1073741823), (1073741824), (2147483646), (2147483647) };
        int[] sh = new int[] { 0, 1, 7, 8, 15, 16, 31, 32, 33, 63, 64, 65, -1 };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            int a = vs[i]; int b = vs[j];
            try { Console.WriteLine("0.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("0.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.1." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("0.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.2." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("0.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.3." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("0.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.4." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("0.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.5." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("0.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.6." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("0.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.7." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("0.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.8." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("0.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.9." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("0.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.10." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("0.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.11." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("0.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.12." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("0.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.13." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("0.13." + i + "." + j + "=!" + e.GetType().Name); }
        }
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < sh.Length; j++) {
            int a = vs[i]; int n = sh[j];
            try { Console.WriteLine("0.100." + i + "." + j + "=" + R((long)(a << n))); }
            catch (Exception e) { Console.WriteLine("0.100." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.101." + i + "." + j + "=" + R((long)(a >> n))); }
            catch (Exception e) { Console.WriteLine("0.101." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.102." + i + "." + j + "=" + R((long)(~a))); }
            catch (Exception e) { Console.WriteLine("0.102." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("0.103." + i + "." + j + "=" + R((long)(unchecked(-a)))); }
            catch (Exception e) { Console.WriteLine("0.103." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T1_uint() {
        uint[] vs = new uint[] { 0U, 1U, 2U, 3U, 7U, 10U, 100U, 255U, 256U, 65535U, 65536U, 2147483647U, 2147483648U, 4294967294U, 4294967295U };
        int[] sh = new int[] { 0, 1, 7, 8, 15, 16, 31, 32, 33, 63, 64, 65, -1 };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            uint a = vs[i]; uint b = vs[j];
            try { Console.WriteLine("1.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("1.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.1." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("1.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.2." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("1.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.3." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("1.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.4." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("1.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.5." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("1.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.6." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("1.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.7." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("1.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.8." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("1.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.9." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("1.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.10." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("1.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.11." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("1.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.12." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("1.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.13." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("1.13." + i + "." + j + "=!" + e.GetType().Name); }
        }
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < sh.Length; j++) {
            uint a = vs[i]; int n = sh[j];
            try { Console.WriteLine("1.100." + i + "." + j + "=" + R((long)(a << n))); }
            catch (Exception e) { Console.WriteLine("1.100." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.101." + i + "." + j + "=" + R((long)(a >> n))); }
            catch (Exception e) { Console.WriteLine("1.101." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("1.102." + i + "." + j + "=" + R((long)(~a))); }
            catch (Exception e) { Console.WriteLine("1.102." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T2_long() {
        long[] vs = new long[] { long.MinValue, (-9223372036854775807L), (-4611686018427387904L), (-2147483648L), (-256L), (-255L), (-100L), (-10L), (-7L), (-3L), (-2L), (-1L), (0L), (1L), (2L), (3L), (7L), (10L), (100L), (255L), (256L), (65535L), (65536L), (2147483647L), (2147483648L), (4294967295L), (4611686018427387903L), (4611686018427387904L), (9223372036854775806L), (9223372036854775807L) };
        int[] sh = new int[] { 0, 1, 7, 8, 15, 16, 31, 32, 33, 63, 64, 65, -1 };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            long a = vs[i]; long b = vs[j];
            try { Console.WriteLine("2.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("2.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.1." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("2.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.2." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("2.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.3." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("2.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.4." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("2.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.5." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("2.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.6." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("2.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.7." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("2.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.8." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("2.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.9." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("2.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.10." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("2.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.11." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("2.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.12." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("2.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.13." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("2.13." + i + "." + j + "=!" + e.GetType().Name); }
        }
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < sh.Length; j++) {
            long a = vs[i]; int n = sh[j];
            try { Console.WriteLine("2.100." + i + "." + j + "=" + R((long)(a << n))); }
            catch (Exception e) { Console.WriteLine("2.100." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.101." + i + "." + j + "=" + R((long)(a >> n))); }
            catch (Exception e) { Console.WriteLine("2.101." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.102." + i + "." + j + "=" + R((long)(~a))); }
            catch (Exception e) { Console.WriteLine("2.102." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("2.103." + i + "." + j + "=" + R((long)(unchecked(-a)))); }
            catch (Exception e) { Console.WriteLine("2.103." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T3_ulong() {
        ulong[] vs = new ulong[] { 0UL, 1UL, 2UL, 3UL, 7UL, 10UL, 100UL, 255UL, 256UL, 65535UL, 65536UL, 2147483647UL, 2147483648UL, 4294967295UL, 9223372036854775807UL, 9223372036854775808UL, 18446744073709551614UL, 18446744073709551615UL };
        int[] sh = new int[] { 0, 1, 7, 8, 15, 16, 31, 32, 33, 63, 64, 65, -1 };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            ulong a = vs[i]; ulong b = vs[j];
            try { Console.WriteLine("3.0." + i + "." + j + "=" + R((ulong)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("3.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.1." + i + "." + j + "=" + R((ulong)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("3.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.2." + i + "." + j + "=" + R((ulong)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("3.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.3." + i + "." + j + "=" + R((ulong)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("3.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.4." + i + "." + j + "=" + R((ulong)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("3.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.5." + i + "." + j + "=" + R((ulong)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("3.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.6." + i + "." + j + "=" + R((ulong)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("3.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.7." + i + "." + j + "=" + R((ulong)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("3.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.8." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("3.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.9." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("3.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.10." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("3.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.11." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("3.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.12." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("3.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.13." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("3.13." + i + "." + j + "=!" + e.GetType().Name); }
        }
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < sh.Length; j++) {
            ulong a = vs[i]; int n = sh[j];
            try { Console.WriteLine("3.100." + i + "." + j + "=" + R((ulong)(a << n))); }
            catch (Exception e) { Console.WriteLine("3.100." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.101." + i + "." + j + "=" + R((ulong)(a >> n))); }
            catch (Exception e) { Console.WriteLine("3.101." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("3.102." + i + "." + j + "=" + R((ulong)(~a))); }
            catch (Exception e) { Console.WriteLine("3.102." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T4_float() {
        float[] vs = new float[] { (float)(0.0), (float)(-0.0), (float)(1.0), (float)(-1.0), (float)(0.5), (float)(-0.5), (float)(2.0), (float)(3.0), (float)(-3.0), (float)(7.5), (float)(-7.5), (float)(1024.25), (float)(-1024.25), (float)(100000.0), (float)(1.0e10), (float)(-1.0e10), (float)(9007199254740992.0), (float)(1.0e30), (float)(-1.0e30), (float)(double.NaN), (float)(double.PositiveInfinity), (float)(double.NegativeInfinity) };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            float a = vs[i]; float b = vs[j];
            try { Console.WriteLine("4.0." + i + "." + j + "=" + F((double)(a + b))); }
            catch (Exception e) { Console.WriteLine("4.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.1." + i + "." + j + "=" + F((double)(a - b))); }
            catch (Exception e) { Console.WriteLine("4.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.2." + i + "." + j + "=" + F((double)(a * b))); }
            catch (Exception e) { Console.WriteLine("4.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.3." + i + "." + j + "=" + F((double)(a / b))); }
            catch (Exception e) { Console.WriteLine("4.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.4." + i + "." + j + "=" + F((double)(a % b))); }
            catch (Exception e) { Console.WriteLine("4.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.5." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("4.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.6." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("4.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.7." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("4.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.8." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("4.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.9." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("4.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.10." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("4.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("4.11." + i + "." + j + "=" + F((double)(-a))); }
            catch (Exception e) { Console.WriteLine("4.11." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T5_double() {
        double[] vs = new double[] { 0.0, -0.0, 1.0, -1.0, 0.5, -0.5, 2.0, 3.0, -3.0, 7.5, -7.5, 1024.25, -1024.25, 100000.0, 1.0e10, -1.0e10, 9007199254740992.0, 1.0e30, -1.0e30, double.NaN, double.PositiveInfinity, double.NegativeInfinity };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            double a = vs[i]; double b = vs[j];
            try { Console.WriteLine("5.0." + i + "." + j + "=" + F((double)(a + b))); }
            catch (Exception e) { Console.WriteLine("5.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.1." + i + "." + j + "=" + F((double)(a - b))); }
            catch (Exception e) { Console.WriteLine("5.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.2." + i + "." + j + "=" + F((double)(a * b))); }
            catch (Exception e) { Console.WriteLine("5.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.3." + i + "." + j + "=" + F((double)(a / b))); }
            catch (Exception e) { Console.WriteLine("5.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.4." + i + "." + j + "=" + F((double)(a % b))); }
            catch (Exception e) { Console.WriteLine("5.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.5." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("5.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.6." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("5.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.7." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("5.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.8." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("5.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.9." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("5.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.10." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("5.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("5.11." + i + "." + j + "=" + F((double)(-a))); }
            catch (Exception e) { Console.WriteLine("5.11." + i + "." + j + "=!" + e.GetType().Name); }
        }
    }
    static void T6_sbyte() {
        sbyte[] vs = new sbyte[] { ((sbyte)-128), ((sbyte)-127), ((sbyte)-100), ((sbyte)-64), ((sbyte)-10), ((sbyte)-7), ((sbyte)-3), ((sbyte)-2), ((sbyte)-1), ((sbyte)0), ((sbyte)1), ((sbyte)2), ((sbyte)3), ((sbyte)7), ((sbyte)10), ((sbyte)63), ((sbyte)64), ((sbyte)100), ((sbyte)126), ((sbyte)127) };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            sbyte a = vs[i]; sbyte b = vs[j];
            try { Console.WriteLine("6.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("6.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.1." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a + b))))); }
            catch (Exception e) { Console.WriteLine("6.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c + b)); Console.WriteLine("6.2." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.3." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("6.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.4." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a - b))))); }
            catch (Exception e) { Console.WriteLine("6.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c - b)); Console.WriteLine("6.5." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.6." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("6.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.7." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a * b))))); }
            catch (Exception e) { Console.WriteLine("6.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c * b)); Console.WriteLine("6.8." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.9." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("6.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.10." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a / b))))); }
            catch (Exception e) { Console.WriteLine("6.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c / b)); Console.WriteLine("6.11." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.12." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("6.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.13." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a % b))))); }
            catch (Exception e) { Console.WriteLine("6.13." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c % b)); Console.WriteLine("6.14." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.14." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.15." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("6.15." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.16." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a & b))))); }
            catch (Exception e) { Console.WriteLine("6.16." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c & b)); Console.WriteLine("6.17." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.17." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.18." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("6.18." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.19." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a | b))))); }
            catch (Exception e) { Console.WriteLine("6.19." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c | b)); Console.WriteLine("6.20." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.20." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.21." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("6.21." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.22." + i + "." + j + "=" + R((long)(unchecked((sbyte)(a ^ b))))); }
            catch (Exception e) { Console.WriteLine("6.22." + i + "." + j + "=!" + e.GetType().Name); }
            try { sbyte c = a; c = unchecked((sbyte)(c ^ b)); Console.WriteLine("6.23." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("6.23." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.24." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("6.24." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.25." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("6.25." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.26." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("6.26." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.27." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("6.27." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.28." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("6.28." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("6.29." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("6.29." + i + "." + j + "=!" + e.GetType().Name); }
            { sbyte c = a; c++; Console.WriteLine("6.30." + i + "." + j + "=" + R((long)c)); }
            { sbyte c = a; c--; Console.WriteLine("6.31." + i + "." + j + "=" + R((long)c)); }
            { sbyte c = a; c = (sbyte)(c << (j & 15)); Console.WriteLine("6.32." + i + "." + j + "=" + R((long)c)); }
            { sbyte c = a; c = (sbyte)(c >> (j & 15)); Console.WriteLine("6.33." + i + "." + j + "=" + R((long)c)); }
            { sbyte c = a; unchecked { c += b; } Console.WriteLine("6.34." + i + "." + j + "=" + R((long)c)); }
            { sbyte c = a; unchecked { c *= b; } Console.WriteLine("6.35." + i + "." + j + "=" + R((long)c)); }
        }
    }
    static void T7_byte() {
        byte[] vs = new byte[] { ((byte)0), ((byte)1), ((byte)2), ((byte)3), ((byte)7), ((byte)10), ((byte)100), ((byte)127), ((byte)128), ((byte)254), ((byte)255) };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            byte a = vs[i]; byte b = vs[j];
            try { Console.WriteLine("7.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("7.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.1." + i + "." + j + "=" + R((long)(unchecked((byte)(a + b))))); }
            catch (Exception e) { Console.WriteLine("7.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c + b)); Console.WriteLine("7.2." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.3." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("7.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.4." + i + "." + j + "=" + R((long)(unchecked((byte)(a - b))))); }
            catch (Exception e) { Console.WriteLine("7.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c - b)); Console.WriteLine("7.5." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.6." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("7.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.7." + i + "." + j + "=" + R((long)(unchecked((byte)(a * b))))); }
            catch (Exception e) { Console.WriteLine("7.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c * b)); Console.WriteLine("7.8." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.9." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("7.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.10." + i + "." + j + "=" + R((long)(unchecked((byte)(a / b))))); }
            catch (Exception e) { Console.WriteLine("7.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c / b)); Console.WriteLine("7.11." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.12." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("7.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.13." + i + "." + j + "=" + R((long)(unchecked((byte)(a % b))))); }
            catch (Exception e) { Console.WriteLine("7.13." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c % b)); Console.WriteLine("7.14." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.14." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.15." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("7.15." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.16." + i + "." + j + "=" + R((long)(unchecked((byte)(a & b))))); }
            catch (Exception e) { Console.WriteLine("7.16." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c & b)); Console.WriteLine("7.17." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.17." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.18." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("7.18." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.19." + i + "." + j + "=" + R((long)(unchecked((byte)(a | b))))); }
            catch (Exception e) { Console.WriteLine("7.19." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c | b)); Console.WriteLine("7.20." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.20." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.21." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("7.21." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.22." + i + "." + j + "=" + R((long)(unchecked((byte)(a ^ b))))); }
            catch (Exception e) { Console.WriteLine("7.22." + i + "." + j + "=!" + e.GetType().Name); }
            try { byte c = a; c = unchecked((byte)(c ^ b)); Console.WriteLine("7.23." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("7.23." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.24." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("7.24." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.25." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("7.25." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.26." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("7.26." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.27." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("7.27." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.28." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("7.28." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("7.29." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("7.29." + i + "." + j + "=!" + e.GetType().Name); }
            { byte c = a; c++; Console.WriteLine("7.30." + i + "." + j + "=" + R((long)c)); }
            { byte c = a; c--; Console.WriteLine("7.31." + i + "." + j + "=" + R((long)c)); }
            { byte c = a; c = (byte)(c << (j & 15)); Console.WriteLine("7.32." + i + "." + j + "=" + R((long)c)); }
            { byte c = a; c = (byte)(c >> (j & 15)); Console.WriteLine("7.33." + i + "." + j + "=" + R((long)c)); }
            { byte c = a; unchecked { c += b; } Console.WriteLine("7.34." + i + "." + j + "=" + R((long)c)); }
            { byte c = a; unchecked { c *= b; } Console.WriteLine("7.35." + i + "." + j + "=" + R((long)c)); }
        }
    }
    static void T8_short() {
        short[] vs = new short[] { ((short)-32768), ((short)-32767), ((short)-16384), ((short)-256), ((short)-255), ((short)-100), ((short)-10), ((short)-7), ((short)-3), ((short)-2), ((short)-1), ((short)0), ((short)1), ((short)2), ((short)3), ((short)7), ((short)10), ((short)100), ((short)255), ((short)256), ((short)16383), ((short)16384), ((short)32766), ((short)32767) };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            short a = vs[i]; short b = vs[j];
            try { Console.WriteLine("8.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("8.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.1." + i + "." + j + "=" + R((long)(unchecked((short)(a + b))))); }
            catch (Exception e) { Console.WriteLine("8.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c + b)); Console.WriteLine("8.2." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.3." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("8.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.4." + i + "." + j + "=" + R((long)(unchecked((short)(a - b))))); }
            catch (Exception e) { Console.WriteLine("8.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c - b)); Console.WriteLine("8.5." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.6." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("8.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.7." + i + "." + j + "=" + R((long)(unchecked((short)(a * b))))); }
            catch (Exception e) { Console.WriteLine("8.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c * b)); Console.WriteLine("8.8." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.9." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("8.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.10." + i + "." + j + "=" + R((long)(unchecked((short)(a / b))))); }
            catch (Exception e) { Console.WriteLine("8.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c / b)); Console.WriteLine("8.11." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.12." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("8.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.13." + i + "." + j + "=" + R((long)(unchecked((short)(a % b))))); }
            catch (Exception e) { Console.WriteLine("8.13." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c % b)); Console.WriteLine("8.14." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.14." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.15." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("8.15." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.16." + i + "." + j + "=" + R((long)(unchecked((short)(a & b))))); }
            catch (Exception e) { Console.WriteLine("8.16." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c & b)); Console.WriteLine("8.17." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.17." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.18." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("8.18." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.19." + i + "." + j + "=" + R((long)(unchecked((short)(a | b))))); }
            catch (Exception e) { Console.WriteLine("8.19." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c | b)); Console.WriteLine("8.20." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.20." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.21." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("8.21." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.22." + i + "." + j + "=" + R((long)(unchecked((short)(a ^ b))))); }
            catch (Exception e) { Console.WriteLine("8.22." + i + "." + j + "=!" + e.GetType().Name); }
            try { short c = a; c = unchecked((short)(c ^ b)); Console.WriteLine("8.23." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("8.23." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.24." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("8.24." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.25." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("8.25." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.26." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("8.26." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.27." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("8.27." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.28." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("8.28." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("8.29." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("8.29." + i + "." + j + "=!" + e.GetType().Name); }
            { short c = a; c++; Console.WriteLine("8.30." + i + "." + j + "=" + R((long)c)); }
            { short c = a; c--; Console.WriteLine("8.31." + i + "." + j + "=" + R((long)c)); }
            { short c = a; c = (short)(c << (j & 15)); Console.WriteLine("8.32." + i + "." + j + "=" + R((long)c)); }
            { short c = a; c = (short)(c >> (j & 15)); Console.WriteLine("8.33." + i + "." + j + "=" + R((long)c)); }
            { short c = a; unchecked { c += b; } Console.WriteLine("8.34." + i + "." + j + "=" + R((long)c)); }
            { short c = a; unchecked { c *= b; } Console.WriteLine("8.35." + i + "." + j + "=" + R((long)c)); }
        }
    }
    static void T9_ushort() {
        ushort[] vs = new ushort[] { ((ushort)0), ((ushort)1), ((ushort)2), ((ushort)3), ((ushort)7), ((ushort)10), ((ushort)100), ((ushort)255), ((ushort)256), ((ushort)32767), ((ushort)32768), ((ushort)65534), ((ushort)65535) };
        for (int i = 0; i < vs.Length; i++) for (int j = 0; j < vs.Length; j++) {
            ushort a = vs[i]; ushort b = vs[j];
            try { Console.WriteLine("9.0." + i + "." + j + "=" + R((long)(unchecked(a + b)))); }
            catch (Exception e) { Console.WriteLine("9.0." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.1." + i + "." + j + "=" + R((long)(unchecked((ushort)(a + b))))); }
            catch (Exception e) { Console.WriteLine("9.1." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c + b)); Console.WriteLine("9.2." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.2." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.3." + i + "." + j + "=" + R((long)(unchecked(a - b)))); }
            catch (Exception e) { Console.WriteLine("9.3." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.4." + i + "." + j + "=" + R((long)(unchecked((ushort)(a - b))))); }
            catch (Exception e) { Console.WriteLine("9.4." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c - b)); Console.WriteLine("9.5." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.5." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.6." + i + "." + j + "=" + R((long)(unchecked(a * b)))); }
            catch (Exception e) { Console.WriteLine("9.6." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.7." + i + "." + j + "=" + R((long)(unchecked((ushort)(a * b))))); }
            catch (Exception e) { Console.WriteLine("9.7." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c * b)); Console.WriteLine("9.8." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.8." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.9." + i + "." + j + "=" + R((long)(unchecked(a / b)))); }
            catch (Exception e) { Console.WriteLine("9.9." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.10." + i + "." + j + "=" + R((long)(unchecked((ushort)(a / b))))); }
            catch (Exception e) { Console.WriteLine("9.10." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c / b)); Console.WriteLine("9.11." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.11." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.12." + i + "." + j + "=" + R((long)(unchecked(a % b)))); }
            catch (Exception e) { Console.WriteLine("9.12." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.13." + i + "." + j + "=" + R((long)(unchecked((ushort)(a % b))))); }
            catch (Exception e) { Console.WriteLine("9.13." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c % b)); Console.WriteLine("9.14." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.14." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.15." + i + "." + j + "=" + R((long)(unchecked(a & b)))); }
            catch (Exception e) { Console.WriteLine("9.15." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.16." + i + "." + j + "=" + R((long)(unchecked((ushort)(a & b))))); }
            catch (Exception e) { Console.WriteLine("9.16." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c & b)); Console.WriteLine("9.17." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.17." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.18." + i + "." + j + "=" + R((long)(unchecked(a | b)))); }
            catch (Exception e) { Console.WriteLine("9.18." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.19." + i + "." + j + "=" + R((long)(unchecked((ushort)(a | b))))); }
            catch (Exception e) { Console.WriteLine("9.19." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c | b)); Console.WriteLine("9.20." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.20." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.21." + i + "." + j + "=" + R((long)(unchecked(a ^ b)))); }
            catch (Exception e) { Console.WriteLine("9.21." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.22." + i + "." + j + "=" + R((long)(unchecked((ushort)(a ^ b))))); }
            catch (Exception e) { Console.WriteLine("9.22." + i + "." + j + "=!" + e.GetType().Name); }
            try { ushort c = a; c = unchecked((ushort)(c ^ b)); Console.WriteLine("9.23." + i + "." + j + "=" + R((long)c)); }
            catch (Exception e) { Console.WriteLine("9.23." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.24." + i + "." + j + "=" + B(a < b)); }
            catch (Exception e) { Console.WriteLine("9.24." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.25." + i + "." + j + "=" + B(a > b)); }
            catch (Exception e) { Console.WriteLine("9.25." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.26." + i + "." + j + "=" + B(a == b)); }
            catch (Exception e) { Console.WriteLine("9.26." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.27." + i + "." + j + "=" + B(a <= b)); }
            catch (Exception e) { Console.WriteLine("9.27." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.28." + i + "." + j + "=" + B(a >= b)); }
            catch (Exception e) { Console.WriteLine("9.28." + i + "." + j + "=!" + e.GetType().Name); }
            try { Console.WriteLine("9.29." + i + "." + j + "=" + B(a != b)); }
            catch (Exception e) { Console.WriteLine("9.29." + i + "." + j + "=!" + e.GetType().Name); }
            { ushort c = a; c++; Console.WriteLine("9.30." + i + "." + j + "=" + R((long)c)); }
            { ushort c = a; c--; Console.WriteLine("9.31." + i + "." + j + "=" + R((long)c)); }
            { ushort c = a; c = (ushort)(c << (j & 15)); Console.WriteLine("9.32." + i + "." + j + "=" + R((long)c)); }
            { ushort c = a; c = (ushort)(c >> (j & 15)); Console.WriteLine("9.33." + i + "." + j + "=" + R((long)c)); }
            { ushort c = a; unchecked { c += b; } Console.WriteLine("9.34." + i + "." + j + "=" + R((long)c)); }
            { ushort c = a; unchecked { c *= b; } Console.WriteLine("9.35." + i + "." + j + "=" + R((long)c)); }
        }
    }
    public static int Main() {
        T0_int();
        T1_uint();
        T2_long();
        T3_ulong();
        T4_float();
        T5_double();
        T6_sbyte();
        T7_byte();
        T8_short();
        T9_ushort();
        return 0;
    }
}
