// GENERATED by tests/gen_checked_conversions.py -- do not edit.
using System;

class Program {
    static string R(long v) { return v.ToString(); }
    static string R(ulong v) { return v.ToString(); }
    static void S0_sbyte(int si) {
        sbyte[] vs = new sbyte[] { ((sbyte)-128), ((sbyte)-127), ((sbyte)-1), ((sbyte)0), ((sbyte)1), ((sbyte)126), ((sbyte)127) };
        for (int n = 0; n < vs.Length; n++) {
            sbyte v = vs[n];
            try { Console.WriteLine("0.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("0.0." + n + "=OVF"); }
            try { Console.WriteLine("0.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("0.1." + n + "=OVF"); }
            try { Console.WriteLine("0.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("0.2." + n + "=OVF"); }
            try { Console.WriteLine("0.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("0.3." + n + "=OVF"); }
            try { Console.WriteLine("0.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("0.4." + n + "=OVF"); }
            try { Console.WriteLine("0.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("0.5." + n + "=OVF"); }
            try { Console.WriteLine("0.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("0.6." + n + "=OVF"); }
            try { Console.WriteLine("0.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("0.7." + n + "=OVF"); }
        }
    }
    static void S1_byte(int si) {
        byte[] vs = new byte[] { ((byte)0), ((byte)1), ((byte)126), ((byte)127), ((byte)128), ((byte)254), ((byte)255) };
        for (int n = 0; n < vs.Length; n++) {
            byte v = vs[n];
            try { Console.WriteLine("1.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("1.0." + n + "=OVF"); }
            try { Console.WriteLine("1.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("1.1." + n + "=OVF"); }
            try { Console.WriteLine("1.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("1.2." + n + "=OVF"); }
            try { Console.WriteLine("1.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("1.3." + n + "=OVF"); }
            try { Console.WriteLine("1.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("1.4." + n + "=OVF"); }
            try { Console.WriteLine("1.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("1.5." + n + "=OVF"); }
            try { Console.WriteLine("1.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("1.6." + n + "=OVF"); }
            try { Console.WriteLine("1.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("1.7." + n + "=OVF"); }
        }
    }
    static void S2_short(int si) {
        short[] vs = new short[] { ((short)-32768), ((short)-32767), ((short)-129), ((short)-128), ((short)-127), ((short)-1), ((short)0), ((short)1), ((short)126), ((short)127), ((short)128), ((short)254), ((short)255), ((short)256), ((short)32766), ((short)32767) };
        for (int n = 0; n < vs.Length; n++) {
            short v = vs[n];
            try { Console.WriteLine("2.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("2.0." + n + "=OVF"); }
            try { Console.WriteLine("2.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("2.1." + n + "=OVF"); }
            try { Console.WriteLine("2.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("2.2." + n + "=OVF"); }
            try { Console.WriteLine("2.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("2.3." + n + "=OVF"); }
            try { Console.WriteLine("2.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("2.4." + n + "=OVF"); }
            try { Console.WriteLine("2.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("2.5." + n + "=OVF"); }
            try { Console.WriteLine("2.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("2.6." + n + "=OVF"); }
            try { Console.WriteLine("2.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("2.7." + n + "=OVF"); }
        }
    }
    static void S3_ushort(int si) {
        ushort[] vs = new ushort[] { ((ushort)0), ((ushort)1), ((ushort)126), ((ushort)127), ((ushort)128), ((ushort)254), ((ushort)255), ((ushort)256), ((ushort)32766), ((ushort)32767), ((ushort)32768), ((ushort)65534), ((ushort)65535) };
        for (int n = 0; n < vs.Length; n++) {
            ushort v = vs[n];
            try { Console.WriteLine("3.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("3.0." + n + "=OVF"); }
            try { Console.WriteLine("3.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("3.1." + n + "=OVF"); }
            try { Console.WriteLine("3.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("3.2." + n + "=OVF"); }
            try { Console.WriteLine("3.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("3.3." + n + "=OVF"); }
            try { Console.WriteLine("3.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("3.4." + n + "=OVF"); }
            try { Console.WriteLine("3.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("3.5." + n + "=OVF"); }
            try { Console.WriteLine("3.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("3.6." + n + "=OVF"); }
            try { Console.WriteLine("3.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("3.7." + n + "=OVF"); }
        }
    }
    static void S4_int(int si) {
        int[] vs = new int[] { int.MinValue, (-2147483647), (-32769), (-32768), (-32767), (-129), (-128), (-127), (-1), (0), (1), (126), (127), (128), (254), (255), (256), (32766), (32767), (32768), (65534), (65535), (65536), (2147483646), (2147483647) };
        for (int n = 0; n < vs.Length; n++) {
            int v = vs[n];
            try { Console.WriteLine("4.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("4.0." + n + "=OVF"); }
            try { Console.WriteLine("4.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("4.1." + n + "=OVF"); }
            try { Console.WriteLine("4.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("4.2." + n + "=OVF"); }
            try { Console.WriteLine("4.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("4.3." + n + "=OVF"); }
            try { Console.WriteLine("4.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("4.4." + n + "=OVF"); }
            try { Console.WriteLine("4.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("4.5." + n + "=OVF"); }
            try { Console.WriteLine("4.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("4.6." + n + "=OVF"); }
            try { Console.WriteLine("4.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("4.7." + n + "=OVF"); }
        }
    }
    static void S5_uint(int si) {
        uint[] vs = new uint[] { 0U, 1U, 126U, 127U, 128U, 254U, 255U, 256U, 32766U, 32767U, 32768U, 65534U, 65535U, 65536U, 2147483646U, 2147483647U, 2147483648U, 4294967294U, 4294967295U };
        for (int n = 0; n < vs.Length; n++) {
            uint v = vs[n];
            try { Console.WriteLine("5.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("5.0." + n + "=OVF"); }
            try { Console.WriteLine("5.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("5.1." + n + "=OVF"); }
            try { Console.WriteLine("5.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("5.2." + n + "=OVF"); }
            try { Console.WriteLine("5.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("5.3." + n + "=OVF"); }
            try { Console.WriteLine("5.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("5.4." + n + "=OVF"); }
            try { Console.WriteLine("5.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("5.5." + n + "=OVF"); }
            try { Console.WriteLine("5.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("5.6." + n + "=OVF"); }
            try { Console.WriteLine("5.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("5.7." + n + "=OVF"); }
        }
    }
    static void S6_long(int si) {
        long[] vs = new long[] { long.MinValue, (-9223372036854775807L), (-2147483649L), (-2147483648L), (-2147483647L), (-32769L), (-32768L), (-32767L), (-129L), (-128L), (-127L), (-1L), (0L), (1L), (126L), (127L), (128L), (254L), (255L), (256L), (32766L), (32767L), (32768L), (65534L), (65535L), (65536L), (2147483646L), (2147483647L), (2147483648L), (4294967294L), (4294967295L), (4294967296L), (9223372036854775806L), (9223372036854775807L) };
        for (int n = 0; n < vs.Length; n++) {
            long v = vs[n];
            try { Console.WriteLine("6.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("6.0." + n + "=OVF"); }
            try { Console.WriteLine("6.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("6.1." + n + "=OVF"); }
            try { Console.WriteLine("6.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("6.2." + n + "=OVF"); }
            try { Console.WriteLine("6.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("6.3." + n + "=OVF"); }
            try { Console.WriteLine("6.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("6.4." + n + "=OVF"); }
            try { Console.WriteLine("6.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("6.5." + n + "=OVF"); }
            try { Console.WriteLine("6.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("6.6." + n + "=OVF"); }
            try { Console.WriteLine("6.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("6.7." + n + "=OVF"); }
        }
    }
    static void S7_ulong(int si) {
        ulong[] vs = new ulong[] { 0UL, 1UL, 126UL, 127UL, 128UL, 254UL, 255UL, 256UL, 32766UL, 32767UL, 32768UL, 65534UL, 65535UL, 65536UL, 2147483646UL, 2147483647UL, 2147483648UL, 4294967294UL, 4294967295UL, 4294967296UL, 9223372036854775806UL, 9223372036854775807UL, 9223372036854775808UL, 18446744073709551614UL, 18446744073709551615UL };
        for (int n = 0; n < vs.Length; n++) {
            ulong v = vs[n];
            try { Console.WriteLine("7.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("7.0." + n + "=OVF"); }
            try { Console.WriteLine("7.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("7.1." + n + "=OVF"); }
            try { Console.WriteLine("7.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("7.2." + n + "=OVF"); }
            try { Console.WriteLine("7.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("7.3." + n + "=OVF"); }
            try { Console.WriteLine("7.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("7.4." + n + "=OVF"); }
            try { Console.WriteLine("7.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("7.5." + n + "=OVF"); }
            try { Console.WriteLine("7.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("7.6." + n + "=OVF"); }
            try { Console.WriteLine("7.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("7.7." + n + "=OVF"); }
        }
    }
    static void S8_float(int si) {
        float[] vs = new float[] { (float)0.0, (float)-0.0, (float)0.5, (float)-0.5, (float)1.0, (float)-1.0, (float)2.9, (float)-2.9, (float)127.0, (float)127.9, (float)128.0, (float)-128.0, (float)-128.9, (float)-129.0, (float)255.0, (float)255.5, (float)256.0, (float)32767.9, (float)32768.0, (float)-32768.0, (float)-32769.0, (float)65535.5, (float)65536.0, (float)2147483647.0, (float)2147483648.0, (float)-2147483648.0, (float)-2147483649.0, (float)4294967295.0, (float)4294967296.0, (float)9223372036854775807.0, (float)9223372036854775808.0, (float)-9223372036854775808.0, (float)-9223372036854777856.0, (float)18446744073709551615.0, (float)18446744073709551616.0, (float)1e30, (float)-1e30, float.NaN, float.PositiveInfinity, float.NegativeInfinity };
        for (int n = 0; n < vs.Length; n++) {
            float v = vs[n];
            try { Console.WriteLine("8.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("8.0." + n + "=OVF"); }
            try { Console.WriteLine("8.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("8.1." + n + "=OVF"); }
            try { Console.WriteLine("8.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("8.2." + n + "=OVF"); }
            try { Console.WriteLine("8.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("8.3." + n + "=OVF"); }
            try { Console.WriteLine("8.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("8.4." + n + "=OVF"); }
            try { Console.WriteLine("8.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("8.5." + n + "=OVF"); }
            try { Console.WriteLine("8.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("8.6." + n + "=OVF"); }
            try { Console.WriteLine("8.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("8.7." + n + "=OVF"); }
        }
    }
    static void S9_double(int si) {
        double[] vs = new double[] { 0.0, -0.0, 0.5, -0.5, 1.0, -1.0, 2.9, -2.9, 127.0, 127.9, 128.0, -128.0, -128.9, -129.0, 255.0, 255.5, 256.0, 32767.9, 32768.0, -32768.0, -32769.0, 65535.5, 65536.0, 2147483647.0, 2147483648.0, -2147483648.0, -2147483649.0, 4294967295.0, 4294967296.0, 9223372036854775807.0, 9223372036854775808.0, -9223372036854775808.0, -9223372036854777856.0, 18446744073709551615.0, 18446744073709551616.0, 1e30, -1e30, (double)float.NaN, (double)float.PositiveInfinity, (double)float.NegativeInfinity };
        for (int n = 0; n < vs.Length; n++) {
            double v = vs[n];
            try { Console.WriteLine("9.0." + n + "=" + R((long)checked((sbyte)v))); }
            catch (OverflowException) { Console.WriteLine("9.0." + n + "=OVF"); }
            try { Console.WriteLine("9.1." + n + "=" + R((long)checked((byte)v))); }
            catch (OverflowException) { Console.WriteLine("9.1." + n + "=OVF"); }
            try { Console.WriteLine("9.2." + n + "=" + R((long)checked((short)v))); }
            catch (OverflowException) { Console.WriteLine("9.2." + n + "=OVF"); }
            try { Console.WriteLine("9.3." + n + "=" + R((long)checked((ushort)v))); }
            catch (OverflowException) { Console.WriteLine("9.3." + n + "=OVF"); }
            try { Console.WriteLine("9.4." + n + "=" + R((long)checked((int)v))); }
            catch (OverflowException) { Console.WriteLine("9.4." + n + "=OVF"); }
            try { Console.WriteLine("9.5." + n + "=" + R((long)checked((uint)v))); }
            catch (OverflowException) { Console.WriteLine("9.5." + n + "=OVF"); }
            try { Console.WriteLine("9.6." + n + "=" + R((long)checked((long)v))); }
            catch (OverflowException) { Console.WriteLine("9.6." + n + "=OVF"); }
            try { Console.WriteLine("9.7." + n + "=" + R((ulong)checked((ulong)v))); }
            catch (OverflowException) { Console.WriteLine("9.7." + n + "=OVF"); }
        }
    }
    public static int Main() {
        S0_sbyte(0);
        S1_byte(1);
        S2_short(2);
        S3_ushort(3);
        S4_int(4);
        S5_uint(5);
        S6_long(6);
        S7_ulong(7);
        S8_float(8);
        S9_double(9);
        return 0;
    }
}
