// GENERATED by tests/gen_mathbits.py -- do not edit.
using System;
class Program {
    static uint s = 12345;
    static uint Rnd() { s = s * 1664525u + 1013904223u; return s; }
    static unsafe uint Bits(float f) { if (f != f) return 0x7FC00000u; return *(uint*)&f; }
    static unsafe ulong Bits(double d) { if (d != d) return 0x7FF8000000000000UL; return *(ulong*)&d; }
    static uint Mix(uint h, uint v) { return (h ^ v) * 16777619u; }
    static uint Mix(uint h, ulong v) { return Mix(Mix(h, (uint)v), (uint)(v >> 32)); }
    static unsafe float F(uint b) { return *(float*)&b; }
    static unsafe double D(ulong b) { return *(double*)&b; }
    static float[] fs; static double[] ds;
    static unsafe void Init() {
        int n = 600; fs = new float[n + 40]; ds = new double[n + 40]; int k = 0;
        float[] sf = new float[] { 0f, -0f, 1f, -1f, 0.5f, -0.5f, 2f, -2f, 3.5f, -3.5f, 2.5f, -2.5f, 1.5f, -1.5f, 0.1f, 100f, -100f, 1e10f, -1e10f, 1e-10f, 3.14159265f, 1.5707964f, 6.2831855f, 1e30f, -1e30f, 1e-40f, -1e-40f, float.MaxValue, float.MinValue, float.Epsilon, float.NaN, float.PositiveInfinity, float.NegativeInfinity, 8388608f, 16777216f, 0.99999994f, 1.0000001f, 123456.789f, -0.0001f, 7f };
        for (int i = 0; i < sf.Length; i++) { fs[k] = sf[i]; ds[k] = (double)sf[i]; k++; }
        double[] sd = new double[] { 1e300, -1e300, 1e-300, 2.2250738585072014e-308, 4.9e-324, 0.1, 1e15, 1e16, 4503599627370496.0, 4503599627370497.0 };
        for (int i = 0; i < sd.Length && k < ds.Length; i++) { ds[k] = sd[i]; fs[k] = (float)sd[i]; k++; }
        for (; k < n + 40; k++) {
            uint a = Rnd(); uint b = Rnd();
            float f = F(a); if (f != f || float.IsInfinity(f)) f = (float)(a % 2000) / 8f - 100f;
            int mode = (int)(b % 4);
            if (mode == 1) f = (float)((a % 20001) - 10000) / 100f;
            else if (mode == 2) f = (float)((a % 2001) - 1000) / 1000f;
            else if (mode == 3) f = (float)((a % 400) - 200) + 0.5f;
            fs[k] = f; ds[k] = (double)f * 1.0000001 + 0.0000003;
        }
    }
    static void Main() {
        Init();
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Sin(fs[i]))); Console.WriteLine("MathF.Sin " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Cos(fs[i]))); Console.WriteLine("MathF.Cos " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Tan(fs[i]))); Console.WriteLine("MathF.Tan " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Asin(fs[i]))); Console.WriteLine("MathF.Asin " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Acos(fs[i]))); Console.WriteLine("MathF.Acos " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Atan(fs[i]))); Console.WriteLine("MathF.Atan " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Sinh(fs[i]))); Console.WriteLine("MathF.Sinh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Cosh(fs[i]))); Console.WriteLine("MathF.Cosh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Tanh(fs[i]))); Console.WriteLine("MathF.Tanh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Sqrt(fs[i]))); Console.WriteLine("MathF.Sqrt " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Exp(fs[i]))); Console.WriteLine("MathF.Exp " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Log(fs[i]))); Console.WriteLine("MathF.Log " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Log10(fs[i]))); Console.WriteLine("MathF.Log10 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Log2(fs[i]))); Console.WriteLine("MathF.Log2 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Floor(fs[i]))); Console.WriteLine("MathF.Floor " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Ceiling(fs[i]))); Console.WriteLine("MathF.Ceiling " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Round(fs[i]))); Console.WriteLine("MathF.Round " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Truncate(fs[i]))); Console.WriteLine("MathF.Truncate " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Cbrt(fs[i]))); Console.WriteLine("MathF.Cbrt " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) h = Mix(h, Bits(MathF.Abs(fs[i]))); Console.WriteLine("MathF.Abs " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 7) h = Mix(h, Bits(MathF.Atan2(fs[i], fs[j]))); Console.WriteLine("MathF.Atan2 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 7) h = Mix(h, Bits(MathF.Pow(fs[i], fs[j]))); Console.WriteLine("MathF.Pow " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 7) h = Mix(h, Bits(MathF.IEEERemainder(fs[i], fs[j]))); Console.WriteLine("MathF.IEEERemainder " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 7) h = Mix(h, Bits(MathF.Max(fs[i], fs[j]))); Console.WriteLine("MathF.Max " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 7) h = Mix(h, Bits(MathF.Min(fs[i], fs[j]))); Console.WriteLine("MathF.Min " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Sin(ds[i]))); Console.WriteLine("Math.Sin " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Cos(ds[i]))); Console.WriteLine("Math.Cos " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Tan(ds[i]))); Console.WriteLine("Math.Tan " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Asin(ds[i]))); Console.WriteLine("Math.Asin " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Acos(ds[i]))); Console.WriteLine("Math.Acos " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Atan(ds[i]))); Console.WriteLine("Math.Atan " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Sinh(ds[i]))); Console.WriteLine("Math.Sinh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Cosh(ds[i]))); Console.WriteLine("Math.Cosh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Tanh(ds[i]))); Console.WriteLine("Math.Tanh " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Sqrt(ds[i]))); Console.WriteLine("Math.Sqrt " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Exp(ds[i]))); Console.WriteLine("Math.Exp " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Log(ds[i]))); Console.WriteLine("Math.Log " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Log10(ds[i]))); Console.WriteLine("Math.Log10 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Log2(ds[i]))); Console.WriteLine("Math.Log2 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Floor(ds[i]))); Console.WriteLine("Math.Floor " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Ceiling(ds[i]))); Console.WriteLine("Math.Ceiling " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Round(ds[i]))); Console.WriteLine("Math.Round " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Truncate(ds[i]))); Console.WriteLine("Math.Truncate " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Cbrt(ds[i]))); Console.WriteLine("Math.Cbrt " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) h = Mix(h, Bits(Math.Abs(ds[i]))); Console.WriteLine("Math.Abs " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 7) h = Mix(h, Bits(Math.Atan2(ds[i], ds[j]))); Console.WriteLine("Math.Atan2 " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 7) h = Mix(h, Bits(Math.Pow(ds[i], ds[j]))); Console.WriteLine("Math.Pow " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 7) h = Mix(h, Bits(Math.IEEERemainder(ds[i], ds[j]))); Console.WriteLine("Math.IEEERemainder " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 7) h = Mix(h, Bits(Math.Max(ds[i], ds[j]))); Console.WriteLine("Math.Max " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 7) h = Mix(h, Bits(Math.Min(ds[i], ds[j]))); Console.WriteLine("Math.Min " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) { if (fs[i] != fs[i]) continue; h = Mix(h, (uint)MathF.Sign(fs[i])); h = Mix(h, (uint)Math.Sign(ds[i])); } Console.WriteLine("Sign " + h); }
        { uint h = 2166136261u; for (int i = 0; i < fs.Length; i++) for (int j = 0; j < fs.Length; j += 11) { float lo = fs[i], hi = fs[j]; if (lo != lo || hi != hi || lo > hi) continue; for (int k = 0; k < fs.Length; k += 13) { float v = fs[k]; h = Mix(h, Bits(Math.Clamp(v, lo, hi))); } } Console.WriteLine("Clamp float " + h); }
        { uint h = 2166136261u; for (int i = 0; i < ds.Length; i++) for (int j = 0; j < ds.Length; j += 11) { double lo = ds[i], hi = ds[j]; if (lo != lo || hi != hi || lo > hi) continue; for (int k = 0; k < ds.Length; k += 13) { double v = ds[k]; h = Mix(h, Bits(Math.Clamp(v, lo, hi))); } } Console.WriteLine("Clamp double " + h); }
        { uint h = 2166136261u; for (int a = -40; a <= 40; a += 3) for (int b = -40; b <= 40; b += 5) for (int c = -40; c <= 40; c += 4) { if (a > b) continue; h = Mix(h, (uint)Math.Clamp(c, a, b)); h = Mix(h, (uint)Math.Clamp((long)c, (long)a, (long)b)); h = Mix(h, (uint)Math.Clamp((byte)(c + 50), (byte)(a + 50), (byte)(b + 50))); } Console.WriteLine("Clamp int " + h); }
        bool thrown = false; try { Math.Clamp(1, 5, 2); } catch (ArgumentException) { thrown = true; } Console.WriteLine("Clamp min>max throws " + thrown);
        Console.WriteLine("consts " + Bits(MathF.PI) + " " + Bits(MathF.E) + " " + Bits(MathF.Tau) + " " + Bits(Math.PI) + " " + Bits(Math.E));
    }
}
