// GENERATED by tests/gen_unchecked_conversions.py -- do not edit.
using System;

class Program {
    static string R(long v) { return v.ToString(); }
    static string R(ulong v) { return v.ToString(); }
    static string B(double v) { return v > 0 ? "+BIG" : "-BIG"; }
    static void S0_sbyte() {
        sbyte[] vs = new sbyte[] { ((sbyte)-128), ((sbyte)-127), ((sbyte)-100), ((sbyte)-1), ((sbyte)0), ((sbyte)1), ((sbyte)2), ((sbyte)100), ((sbyte)126), ((sbyte)127) };
        for (int n = 0; n < vs.Length; n++) {
            sbyte v = vs[n];
            Console.WriteLine("0.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("0.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("0.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("0.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("0.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("0.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("0.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("0.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("0.8." + n + "=" + R((long)r)); else Console.WriteLine("0.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("0.9." + n + "=" + R((long)r)); else Console.WriteLine("0.9." + n + "=" + B(r)); }
        }
    }
    static void S1_byte() {
        byte[] vs = new byte[] { ((byte)0), ((byte)1), ((byte)2), ((byte)100), ((byte)126), ((byte)127), ((byte)128), ((byte)254), ((byte)255) };
        for (int n = 0; n < vs.Length; n++) {
            byte v = vs[n];
            Console.WriteLine("1.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("1.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("1.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("1.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("1.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("1.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("1.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("1.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("1.8." + n + "=" + R((long)r)); else Console.WriteLine("1.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("1.9." + n + "=" + R((long)r)); else Console.WriteLine("1.9." + n + "=" + B(r)); }
        }
    }
    static void S2_short() {
        short[] vs = new short[] { ((short)-32768), ((short)-32767), ((short)-129), ((short)-128), ((short)-127), ((short)-100), ((short)-1), ((short)0), ((short)1), ((short)2), ((short)100), ((short)126), ((short)127), ((short)128), ((short)254), ((short)255), ((short)256), ((short)32766), ((short)32767) };
        for (int n = 0; n < vs.Length; n++) {
            short v = vs[n];
            Console.WriteLine("2.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("2.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("2.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("2.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("2.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("2.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("2.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("2.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("2.8." + n + "=" + R((long)r)); else Console.WriteLine("2.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("2.9." + n + "=" + R((long)r)); else Console.WriteLine("2.9." + n + "=" + B(r)); }
        }
    }
    static void S3_ushort() {
        ushort[] vs = new ushort[] { ((ushort)0), ((ushort)1), ((ushort)2), ((ushort)100), ((ushort)126), ((ushort)127), ((ushort)128), ((ushort)254), ((ushort)255), ((ushort)256), ((ushort)32766), ((ushort)32767), ((ushort)32768), ((ushort)65534), ((ushort)65535) };
        for (int n = 0; n < vs.Length; n++) {
            ushort v = vs[n];
            Console.WriteLine("3.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("3.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("3.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("3.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("3.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("3.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("3.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("3.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("3.8." + n + "=" + R((long)r)); else Console.WriteLine("3.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("3.9." + n + "=" + R((long)r)); else Console.WriteLine("3.9." + n + "=" + B(r)); }
        }
    }
    static void S4_int() {
        int[] vs = new int[] { int.MinValue, (-2147483647), (-32769), (-32768), (-32767), (-129), (-128), (-127), (-100), (-1), (0), (1), (2), (100), (126), (127), (128), (254), (255), (256), (32766), (32767), (32768), (65534), (65535), (65536), (2147483646), (2147483647) };
        for (int n = 0; n < vs.Length; n++) {
            int v = vs[n];
            Console.WriteLine("4.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("4.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("4.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("4.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("4.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("4.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("4.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("4.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("4.8." + n + "=" + R((long)r)); else Console.WriteLine("4.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("4.9." + n + "=" + R((long)r)); else Console.WriteLine("4.9." + n + "=" + B(r)); }
        }
    }
    static void S5_uint() {
        uint[] vs = new uint[] { 0U, 1U, 2U, 100U, 126U, 127U, 128U, 254U, 255U, 256U, 32766U, 32767U, 32768U, 65534U, 65535U, 65536U, 2147483646U, 2147483647U, 2147483648U, 4294967294U, 4294967295U };
        for (int n = 0; n < vs.Length; n++) {
            uint v = vs[n];
            Console.WriteLine("5.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("5.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("5.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("5.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("5.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("5.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("5.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("5.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("5.8." + n + "=" + R((long)r)); else Console.WriteLine("5.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("5.9." + n + "=" + R((long)r)); else Console.WriteLine("5.9." + n + "=" + B(r)); }
        }
    }
    static void S6_long() {
        long[] vs = new long[] { long.MinValue, (-9223372036854775807L), (-2147483649L), (-2147483648L), (-2147483647L), (-32769L), (-32768L), (-32767L), (-129L), (-128L), (-127L), (-100L), (-1L), (0L), (1L), (2L), (100L), (126L), (127L), (128L), (254L), (255L), (256L), (32766L), (32767L), (32768L), (65534L), (65535L), (65536L), (2147483646L), (2147483647L), (2147483648L), (4294967294L), (4294967295L), (4294967296L), (9223372036854775806L), (9223372036854775807L) };
        for (int n = 0; n < vs.Length; n++) {
            long v = vs[n];
            Console.WriteLine("6.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("6.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("6.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("6.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("6.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("6.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("6.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("6.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("6.8." + n + "=" + R((long)r)); else Console.WriteLine("6.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("6.9." + n + "=" + R((long)r)); else Console.WriteLine("6.9." + n + "=" + B(r)); }
        }
    }
    static void S7_ulong() {
        ulong[] vs = new ulong[] { 0UL, 1UL, 2UL, 100UL, 126UL, 127UL, 128UL, 254UL, 255UL, 256UL, 32766UL, 32767UL, 32768UL, 65534UL, 65535UL, 65536UL, 2147483646UL, 2147483647UL, 2147483648UL, 4294967294UL, 4294967295UL, 4294967296UL, 9223372036854775806UL, 9223372036854775807UL, 9223372036854775808UL, 18446744073709551614UL, 18446744073709551615UL };
        for (int n = 0; n < vs.Length; n++) {
            ulong v = vs[n];
            Console.WriteLine("7.0." + n + "=" + R((long)unchecked((sbyte)v)));
            Console.WriteLine("7.1." + n + "=" + R((long)unchecked((byte)v)));
            Console.WriteLine("7.2." + n + "=" + R((long)unchecked((short)v)));
            Console.WriteLine("7.3." + n + "=" + R((long)unchecked((ushort)v)));
            Console.WriteLine("7.4." + n + "=" + R((long)unchecked((int)v)));
            Console.WriteLine("7.5." + n + "=" + R((long)unchecked((uint)v)));
            Console.WriteLine("7.6." + n + "=" + R((long)unchecked((long)v)));
            Console.WriteLine("7.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("7.8." + n + "=" + R((long)r)); else Console.WriteLine("7.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("7.9." + n + "=" + R((long)r)); else Console.WriteLine("7.9." + n + "=" + B(r)); }
        }
    }
    static void S8_float() {
        float[] vs = new float[] { (float)(0.0), (float)(0.5), (float)(-0.5), (float)(1.0), (float)(-1.0), (float)(2.9), (float)(-2.9), (float)(127.0), (float)(-127.0), (float)(127.9), (float)(-127.9), (float)(128.0), (float)(-128.0), (float)(-128.9), (float)(255.0), (float)(-255.0), (float)(255.5), (float)(-255.5), (float)(256.0), (float)(-256.0), (float)(32767.9), (float)(-32767.9), (float)(-32768.0), (float)(65535.5), (float)(-65535.5), (float)(65536.0), (float)(-65536.0), (float)(2147483647.0), (float)(-2147483647.0), (float)(-2147483648.0), (float)(4294967295.0), (float)(-4294967295.0), (float)(4294967296.0), (float)(-4294967296.0), (float)(1099511627776.5), (float)(-1099511627776.5), (float)(9007199254740992.0), (float)(-9007199254740992.0), (float)(4.611686018427388e+18), (float)(-4.611686018427388e+18), (float)(9.223372036854775e+18), (float)(-9.223372036854775e+18), (float)(-9.223372036854776e+18), (float)(1e+19), (float)(-1e+19), (float)(1.8e+19), (float)(-1.8e+19) };
        for (int n = 0; n < vs.Length; n++) {
            float v = vs[n];
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 12 || n == 13) Console.WriteLine("8.0." + n + "=" + R((long)unchecked((sbyte)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16) Console.WriteLine("8.1." + n + "=" + R((long)unchecked((byte)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22) Console.WriteLine("8.2." + n + "=" + R((long)unchecked((short)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23) Console.WriteLine("8.3." + n + "=" + R((long)unchecked((ushort)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22 || n == 23 || n == 24 || n == 25 || n == 26 || n == 28 || n == 29) Console.WriteLine("8.4." + n + "=" + R((long)unchecked((int)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23 || n == 25 || n == 27) Console.WriteLine("8.5." + n + "=" + R((long)unchecked((uint)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22 || n == 23 || n == 24 || n == 25 || n == 26 || n == 27 || n == 28 || n == 29 || n == 30 || n == 31 || n == 32 || n == 33 || n == 34 || n == 35 || n == 36 || n == 37 || n == 38 || n == 39 || n == 41 || n == 42) Console.WriteLine("8.6." + n + "=" + R((long)unchecked((long)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23 || n == 25 || n == 27 || n == 30 || n == 32 || n == 34 || n == 36 || n == 38 || n == 40 || n == 43 || n == 45) Console.WriteLine("8.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("8.8." + n + "=" + R((long)r)); else Console.WriteLine("8.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("8.9." + n + "=" + R((long)r)); else Console.WriteLine("8.9." + n + "=" + B(r)); }
        }
    }
    static void S9_double() {
        double[] vs = new double[] { 0.0, 0.5, -0.5, 1.0, -1.0, 2.9, -2.9, 127.0, -127.0, 127.9, -127.9, 128.0, -128.0, -128.9, 255.0, -255.0, 255.5, -255.5, 256.0, -256.0, 32767.9, -32767.9, -32768.0, 65535.5, -65535.5, 65536.0, -65536.0, 2147483647.0, -2147483647.0, -2147483648.0, 4294967295.0, -4294967295.0, 4294967296.0, -4294967296.0, 1099511627776.5, -1099511627776.5, 9007199254740992.0, -9007199254740992.0, 4.611686018427388e+18, -4.611686018427388e+18, 9.223372036854775e+18, -9.223372036854775e+18, -9.223372036854776e+18, 1e+19, -1e+19, 1.8e+19, -1.8e+19 };
        for (int n = 0; n < vs.Length; n++) {
            double v = vs[n];
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 12 || n == 13) Console.WriteLine("9.0." + n + "=" + R((long)unchecked((sbyte)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16) Console.WriteLine("9.1." + n + "=" + R((long)unchecked((byte)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22) Console.WriteLine("9.2." + n + "=" + R((long)unchecked((short)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23) Console.WriteLine("9.3." + n + "=" + R((long)unchecked((ushort)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22 || n == 23 || n == 24 || n == 25 || n == 26 || n == 27 || n == 28 || n == 29) Console.WriteLine("9.4." + n + "=" + R((long)unchecked((int)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23 || n == 25 || n == 27 || n == 30) Console.WriteLine("9.5." + n + "=" + R((long)unchecked((uint)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 4 || n == 5 || n == 6 || n == 7 || n == 8 || n == 9 || n == 10 || n == 11 || n == 12 || n == 13 || n == 14 || n == 15 || n == 16 || n == 17 || n == 18 || n == 19 || n == 20 || n == 21 || n == 22 || n == 23 || n == 24 || n == 25 || n == 26 || n == 27 || n == 28 || n == 29 || n == 30 || n == 31 || n == 32 || n == 33 || n == 34 || n == 35 || n == 36 || n == 37 || n == 38 || n == 39 || n == 40 || n == 41 || n == 42) Console.WriteLine("9.6." + n + "=" + R((long)unchecked((long)v)));
            if (n == 0 || n == 1 || n == 2 || n == 3 || n == 5 || n == 7 || n == 9 || n == 11 || n == 14 || n == 16 || n == 18 || n == 20 || n == 23 || n == 25 || n == 27 || n == 30 || n == 32 || n == 34 || n == 36 || n == 38 || n == 40 || n == 43 || n == 45) Console.WriteLine("9.7." + n + "=" + R((ulong)unchecked((ulong)v)));
            { float r = unchecked((float)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("9.8." + n + "=" + R((long)r)); else Console.WriteLine("9.8." + n + "=" + B(r)); }
            { double r = unchecked((double)v); if (r > -9.0e18 && r < 9.0e18) Console.WriteLine("9.9." + n + "=" + R((long)r)); else Console.WriteLine("9.9." + n + "=" + B(r)); }
        }
    }
    public static int Main() {
        S0_sbyte();
        S1_byte();
        S2_short();
        S3_ushort();
        S4_int();
        S5_uint();
        S6_long();
        S7_ulong();
        S8_float();
        S9_double();
        return 0;
    }
}
