#!/usr/bin/env python3
"""Turn native/stencils/stencils.c into native/src/Stencils.gen.h: machine-code templates ("stencils") with holes.

This is the "copy" and the "patch" of copy-and-patch compilation. gcc compiles stencils.c, which is a set of tiny
functions, each doing what one interpreter instruction does (see that file for the rules). This script reads the
resulting ELF object file, and for every function takes its bytes and the relocations that point into it. A
relocation against the symbol HOLE0 is a hole: a 32-bit field that NativeBlocks.c fills in with an instruction's
operand (a local's offset, a constant). The trailing `ret` is dropped so that stencils can be laid end to end.

The checks (a stencil that breaks one is rejected, because it could not be copied around safely):
  * the code is straight-line: objdump shows no jump, call or ret except the last instruction;
  * every relocation is an absolute 32-bit one (R_X86_64_32 or R_X86_64_32S) against HOLE0 or HOLE1: a reference to
    anything else (a constant in .rodata, another function) would not survive being copied.

    python3 tools/gen_stencils.py            # (re)write native/src/Stencils.gen.h
    python3 tools/gen_stencils.py --check    # fail if it is out of date
    python3 tools/gen_stencils.py --extra-c F.c --extra-names a,b --out H.h
                                             # also compile F.c (st_a, st_b ...) and write H.h instead: what build.py --ffi does (the
                                             # generated ffi_* stencils call a C function, so they may contain one indirect call)

On a host that is not x86-64 Linux (or without gcc) the header says STENCILS_AVAILABLE 0 and the interpreter does not
use native blocks. Setting DNA_NO_STENCILS=1 at run time turns them off too.
"""
import os
import platform
import re
import shutil
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "native", "stencils", "stencils.c")
OUT = os.path.join(HERE, "..", "native", "src", "Stencils.gen.h")

# The stencils the interpreter needs, in the order of the ST_ enum. Each must be a function st_<name> in stencils.c.
NAMES = ["ldl", "stl", "ldc", "fadd", "fsub", "fmul", "fdiv", "fneg", "lda", "ldp", "stp", "dup4", "dup8", "ldfld4", "stfld4",
         "iadd", "isub", "imul", "iand", "ior", "ixor", "ishl", "ishr", "ishrun",
         "j", "jt", "jf", "jeq", "jge", "jgt", "jle", "jlt", "jne",
         "jfeq", "jfne", "jflt", "jfle", "jfgt", "jfge", "jflt_un", "jfle_un", "jfgt_un", "jfge_un", "cvtif", "cvtfi",
         "ldelem4", "ldelemu1", "ldelemb4", "stelem4", "stelem1", "ldelema", "ldlen", "cvtii", "cvtmask",
         "ldc8lo", "ldc8hi", "ladd", "lsub", "lmul", "land", "lor", "lxor", "lshl", "lshr", "lshrun", "lneg",
         "dadd", "dsub", "dmul", "ddiv", "dneg", "cvtil", "cvtul", "cvtli", "cvtid", "cvtdi", "cvtfd", "cvtdf",
         "lbeq", "lbge", "lbgt", "lble", "lblt", "lbne",
         "jdeq", "jdne", "jdlt", "jdle", "jdgt", "jdge", "jdlt_un", "jdle_un", "jdgt_un", "jdge_un",
         "zero4", "zero8", "chkthis", "ldfld8", "stfld8", "ldflda", "cvtld", "cvtlf", "cvtdl", "cvtfl", "jt8", "jf8"]
GCC_FLAGS = ["-O2", "-fno-pic", "-fno-pie", "-mcmodel=small", "-ffixed-r12", "-ffixed-r13",
             "-fno-asynchronous-unwind-tables", "-fno-unwind-tables", "-fcf-protection=none",
             "-fno-stack-protector", "-ffp-contract=off", "-fno-ident"]
R_X86_64_32, R_X86_64_32S = 10, 11
R_X86_64_PC32, R_X86_64_PLT32 = 2, 4     # a jump or call target: only HOLE1 (the exit) and HOLE2 (index out of range) may be one


def unavailable(why):
    return ("// GENERATED by tools/gen_stencils.py. Do not edit.\n// Native blocks are not available here: %s\n"
            "#define STENCILS_AVAILABLE 0\n" % why)


def parse_elf(path):
    """{function name: (bytes, [(offset in function, hole number, addend, type)])} for the functions in .text"""
    data = open(path, "rb").read()
    if data[:4] != b"\x7fELF" or data[4] != 2 or data[5] != 1:
        sys.exit("not a 64-bit little-endian ELF object")
    shoff, = struct.unpack_from("<Q", data, 0x28)
    shentsize, shnum, shstrndx = struct.unpack_from("<HHH", data, 0x3A)
    secs = []
    for i in range(shnum):
        name, typ, flags, addr, off, size, link, info, align, entsize = struct.unpack_from("<IIQQQQIIQQ", data, shoff + i * shentsize)
        secs.append(dict(name=name, type=typ, off=off, size=size, link=link, info=info, entsize=entsize))
    shstr = secs[shstrndx]

    def sname(sec):
        start = shstr["off"] + sec["name"]
        return data[start:data.index(b"\0", start)].decode()

    text_idx = next(i for i, s in enumerate(secs) if sname(s) == ".text")
    text = secs[text_idx]
    symtab = next(s for s in secs if s["type"] == 2)         # SHT_SYMTAB
    strtab = secs[symtab["link"]]

    def symname(idx):
        n, = struct.unpack_from("<I", data, symtab["off"] + idx * 24)
        start = strtab["off"] + n
        return data[start:data.index(b"\0", start)].decode()

    funcs = {}
    for i in range(symtab["size"] // 24):
        st_name, st_info, st_other, st_shndx, st_value, st_size = struct.unpack_from("<IBBHQQ", data, symtab["off"] + i * 24)
        if (st_info & 0xf) == 2 and st_shndx == text_idx:   # STT_FUNC in .text
            funcs[symname(i)] = (st_value, st_size)

    relocs = []
    for s in secs:
        if s["type"] == 4 and s["info"] == text_idx:         # SHT_RELA for .text
            for j in range(s["size"] // 24):
                r_off, r_info, r_add = struct.unpack_from("<QQq", data, s["off"] + j * 24)
                relocs.append((r_off, r_info >> 32, r_info & 0xffffffff, r_add))

    out = {}
    for name, (value, size) in funcs.items():
        code = data[text["off"] + value: text["off"] + value + size]
        holes = []
        for r_off, sym, typ, add in relocs:
            if value <= r_off < value + size:
                target = symname(sym)
                m = re.fullmatch(r"HOLE(\d)", target)
                is_abs = typ in (R_X86_64_32, R_X86_64_32S)
                is_rel = typ in (R_X86_64_PC32, R_X86_64_PLT32)
                if not m or not (is_abs or (is_rel and target in ("HOLE1", "HOLE2", "HOLE5"))):
                    sys.exit("stencil %s has a relocation (type %d against %s) that cannot be copied: only absolute "
                             "32-bit references to HOLEn, and PC-relative branches to HOLE1 or HOLE2 (or a read of the constant pool, HOLE5), are allowed" % (name, typ, target))
                holes.append((r_off - value, int(m.group(1)), add, 1 if is_rel else 0))
        out[name] = (code, sorted(holes))
    return out


def check_straight_line(obj, names, branch_relocs):
    # (a stencil called ffi_* calls a C function: through a register, once)
    """objdump the object: the only control transfer in each function is its final ret"""
    asm = subprocess.run(["objdump", "-d", "--no-show-raw-insn", obj], capture_output=True, text=True).stdout
    current, insns = None, {}
    for line in asm.splitlines():
        m = re.match(r"^[0-9a-f]+ <(\w+)>:", line)
        if m:
            current = m.group(1)
            insns[current] = []
            continue
        m = re.match(r"^\s+[0-9a-f]+:\t(\S+)", line)
        if m and current:
            insns[current].append(m.group(1))
    for n in names:
        seq = insns.get("st_" + n)
        if not seq:
            sys.exit("no code for stencil st_%s" % n)
        # the function may be followed by padding (nop / data16 / xchg): look only at up to its first ret
        if "ret" not in seq:
            sys.exit("stencil st_%s has no ret" % n)
        body = seq[:seq.index("ret")]
        jumps = 0
        for mnem in body:
            if mnem == "call" and n.startswith("ffi_") and body.count("call") == 1:
                continue
            if mnem.startswith("call") or mnem.startswith("ret") or mnem == "loop":
                sys.exit("stencil st_%s is not straight-line code (it has a %s)" % (n, mnem))
            if mnem.startswith("j"):
                jumps += 1
        if jumps != branch_relocs.get(n, 0):
            sys.exit("stencil st_%s has %d jump(s) but %d branch relocation(s) to HOLE1: every jump must be an exit "
                     "to the block's stub" % (n, jumps, branch_relocs.get(n, 0)))


def vstencil_names():
    """the register stencils (tools/gen_vstencils.py writes their names beside their source, which stencils.c includes)"""
    path = os.path.join(HERE, "..", "native", "stencils", "vstencils.json")
    if not os.path.exists(path):
        sys.exit("native/stencils/vstencils.json is missing: run tools/gen_vstencils.py first")
    import json
    return json.load(open(path))


def generate(extra_c=None, extra_names=()):
    names_all = list(NAMES) + vstencil_names() + list(extra_names)
    if platform.machine() not in ("x86_64", "AMD64") or platform.system() != "Linux":
        return unavailable("this host is %s %s; stencils are x86-64 Linux" % (platform.system(), platform.machine()))
    for tool in ("gcc", "objdump"):
        if shutil.which(tool) is None:
            return unavailable("%s was not found (stencils need gcc and objdump from binutils)" % tool)
    with tempfile.TemporaryDirectory() as d:
        obj = os.path.join(d, "stencils.o")
        src = SRC
        if extra_c:
            # one translation unit: the stencils, then the generated ones (which use the same register conventions)
            src = os.path.join(d, "combined.c")
            open(src, "w").write('#include "%s"\n#include "%s"\n' % (os.path.abspath(SRC), os.path.abspath(extra_c)))
        r = subprocess.run(["gcc"] + GCC_FLAGS + ["-c", src, "-o", obj], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("gcc failed on stencils.c:\n" + r.stderr)
        funcs = parse_elf(obj)
        for n in list(funcs):
            code, holes = funcs[n]
            if code.endswith(b"\xc3\x0f\x0b"):
                # gcc puts a ud2 after the asm of a naked function: not part of the stencil (cut here, once, so the length is right everywhere)
                funcs[n] = (code[:-2], holes)
        branch_relocs = dict((n[3:], sum(1 for h in holes if h[3] == 1 and h[1] in (1, 2))) for n, (code, holes) in funcs.items())
        check_straight_line(obj, names_all, branch_relocs)
    o = ["// GENERATED by tools/gen_stencils.py from native/stencils/stencils.c. Do not edit.", "",
         "#define STENCILS_AVAILABLE 1", "",
         "#ifndef STENCIL_IDS_DEFINED", "#define STENCIL_IDS_DEFINED",
         "enum { " + ", ".join("ST_" + n.upper() for n in names_all) + ", ST_COUNT };",
         "#endif", "",
         "// The code itself is only wanted by NativeBlocks.c, which defines STENCIL_DATA first", "#ifdef STENCIL_DATA", "",
         "typedef struct { unsigned off; unsigned hole; int addend; int rel; } tStencilHole;   // rel: a PC-relative branch",
         "typedef struct { const unsigned char *code; unsigned len; unsigned numHoles; tStencilHole holes[6]; } tStencil;", ""]
    for n in names_all:
        if "st_" + n not in funcs:
            sys.exit("stencils.c has no function st_%s" % n)
        code, holes = funcs["st_" + n]
        if code[-1] != 0xC3:
            sys.exit("st_%s does not end in ret" % n)
        code = code[:-1]
        if len(holes) > 6:
            sys.exit("st_%s has more than six holes" % n)
        for off, hole, add, typ in holes:
            if off + 4 > len(code):
                sys.exit("st_%s: a hole runs into the ret" % n)
        o.append("static const unsigned char stencil_%s[] = { %s };" % (n, ", ".join("0x%02x" % b for b in code) if code else "0"))
    o.append("")
    o.append("static const tStencil stencils[ST_COUNT] = {")
    for n in names_all:
        code, holes = funcs["st_" + n]
        hs = ", ".join("{ %d, %d, %d, %d }" % (off, hole, add, rel) for off, hole, add, rel in holes)
        o.append("\t{ stencil_%s, %d, %d, { %s } }," % (n, len(code) - 1, len(holes), hs))
    o.append("};")
    o.append("static const char *const stencilNames[ST_COUNT] = { " + ", ".join('"%s"' % n for n in names_all) + " };")
    o.append("")
    o.append("#endif // STENCIL_DATA")
    return "\n".join(o) + "\n"


def arg(flag):
    return sys.argv[sys.argv.index(flag) + 1] if flag in sys.argv else None


if __name__ == "__main__":
    if arg("--out"):
        OUT = arg("--out")
    text = generate(arg("--extra-c"), [n for n in (arg("--extra-names") or "").split(",") if n])
    if "--check" in sys.argv:
        if not (os.path.exists(OUT) and open(OUT).read() == text):
            sys.exit("Stencils.gen.h is out of date: run tools/gen_stencils.py")
        print("Stencils.gen.h is up to date")
    elif os.path.exists(OUT) and open(OUT).read() == text:
        print("unchanged")
    else:
        open(OUT, "w").write(text)
        print("wrote", os.path.relpath(OUT))
