#!/usr/bin/env python3
"""Generate the fused ("super") instructions of the interpreter.

A .NET method is a stack machine: `a = b + c` is ldloc, ldloc, add, stloc, four instructions that each cost a
dispatch and push or pop the evaluation stack. After the JIT has translated a method (JITit in JIT.c), a pass looks for
runs of instructions that have a fused equivalent and replaces each run with ONE instruction that reads its operands
straight from the locals. This script writes everything that has to agree about those instructions:

    native/src/JIT_FusedOps.gen.h   the opcode numbers (included by JIT_OpCodes.h)
    native/src/JIT_Fused.gen.h      three sections, selected by a macro the includer defines:
                                      FUSED_HANDLERS  the interpreter code for each fused instruction
                                      FUSED_LABELS    registering each handler's address
                                      FUSED_TABLES    what the JIT matches (unfused op -> its fused forms)

Operand forms. "L" is a local or argument (a byte offset into the frame's parameters-and-locals), "C" a 32-bit constant:

    BIN_LL   ldloc a; ldloc b; <op>                 -> [fused][a][b]           pushes the result
    BIN_LC   ldloc a; ldc k;   <op>                 -> [fused][a][k]
    BCC_LL   ldloc a; ldloc b; <compare-and-branch> -> [fused][a][b][target]
    BCC_LC   ldloc a; ldc k;   <compare-and-branch> -> [fused][a][k][target]
    INC_L    ldloc a; ldc k; add; stloc a           -> [fused][a][k]           a += k in place
    LOAD2    ldloc a; ldloc b                       -> [fused][a][b]

To add a fused instruction, add it to the tables below and regenerate (build.py does that when this file changes).
Whether fusion is used at all can be switched off at run time with the environment variable DNA_NO_FUSION=1, which is
how to tell if a miscompile is the fusion pass's doing.

    python3 tools/gen_fused_ops.py            # (re)write the two headers
    python3 tools/gen_fused_ops.py --check    # fail if they are out of date
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "native", "src")
OUT_OPS = os.path.join(SRC, "JIT_FusedOps.gen.h")
OUT = os.path.join(SRC, "JIT_Fused.gen.h")

FIRST_OPCODE = 0x17a      # the first free number after the hand-written ones (JIT_OpCodes.h)

# (name, the unfused op, C expression on U32 a, b)
I32_BIN = [
    ("ADD", "JIT_ADD_I32I32", "a + b"),
    ("SUB", "JIT_SUB_I32I32", "a - b"),
    ("MUL", "JIT_MUL_I32I32", "a * b"),
    ("AND", "JIT_AND_I32I32", "a & b"),
    ("OR", "JIT_OR_I32I32", "a | b"),
    ("XOR", "JIT_XOR_I32I32", "a ^ b"),
    ("SHL", "JIT_SHL_I32", "a << b"),
    ("SHR", "JIT_SHR_I32", "(U32)((I32)a >> b)"),
    ("SHR_UN", "JIT_SHR_UN_I32", "a >> b"),
]
# Shifts get only the constant-count form: C# masks a variable shift count (a << (b & 31)), so the IL for a shift by
# a local never occurs, and a handler that can never run is a handler that cannot be tested.
LC_ONLY = {"SHL", "SHR", "SHR_UN"}

# (name, the unfused op, C expression on float a, b)
F32_BIN = [
    ("ADD", "JIT_ADD_F32F32", "a + b"),
    ("SUB", "JIT_SUB_F32F32", "a - b"),
    ("MUL", "JIT_MUL_F32F32", "a * b"),
    ("DIV", "JIT_DIV_F32F32", "a / b"),
]
# (name, the unfused op, C condition on U32 a, b)
I32_BCC = [
    ("BEQ", "JIT_BEQ_I32I32", "a == b"),
    ("BGE", "JIT_BGE_I32I32", "(I32)a >= (I32)b"),
    ("BGT", "JIT_BGT_I32I32", "(I32)a > (I32)b"),
    ("BLE", "JIT_BLE_I32I32", "(I32)a <= (I32)b"),
    ("BLT", "JIT_BLT_I32I32", "(I32)a < (I32)b"),
    ("BNE_UN", "JIT_BNE_UN_I32I32", "a != b"),
]


def all_ops():
    """[(fused op name, kind)] in numbering order"""
    ops = []
    for n, _, _ in I32_BIN:
        if n not in LC_ONLY:
            ops.append(("JIT_FUSED_I32_%s_LL" % n, "i32bin_ll"))
        ops.append(("JIT_FUSED_I32_%s_LC" % n, "i32bin_lc"))
    for n, _, _ in F32_BIN:
        ops += [("JIT_FUSED_F32_%s_LL" % n, "f32bin_ll"), ("JIT_FUSED_F32_%s_LC" % n, "f32bin_lc")]
    for n, _, _ in I32_BCC:
        ops += [("JIT_FUSED_I32_%s_LL" % n, "bcc_ll"), ("JIT_FUSED_I32_%s_LC" % n, "bcc_lc")]
    ops += [("JIT_FUSED_INC_L", "inc"), ("JIT_FUSED_LOAD2", "load2")]
    return ops


def gen_ops_header():
    o = ["// GENERATED by tools/gen_fused_ops.py. Do not edit: change the tables there and regenerate.", ""]
    ops = all_ops()
    for i, (name, _) in enumerate(ops):
        o.append("#define %-32s 0x%x" % (name, FIRST_OPCODE + i))
    o.append("")
    o.append("#define JIT_FUSED_COUNT %d" % len(ops))
    if FIRST_OPCODE + len(ops) > 512:
        sys.exit("too many fused instructions for the 9-bit opcode space")
    return "\n".join(o) + "\n"


def handler(name, body, branch=False):
    end = "GO_NEXT_CHECK();" if branch else "GO_NEXT();"
    return "%s_start:\n\tOPCODE_USE(%s);\n\t{\n%s\n\t}\n%s_end:\n\t%s\n" % (name, name, body, name, end)


def gen_handlers():
    h = []
    for n, _, expr in I32_BIN:
        if n not in LC_ONLY:
            h.append(handler("JIT_FUSED_I32_%s_LL" % n, "\t\tU32 a = PARAMLOCAL_U32(GET_OP());\n\t\tU32 b = PARAMLOCAL_U32(GET_OP());\n\t\tPUSH_U32(%s);" % expr))
        h.append(handler("JIT_FUSED_I32_%s_LC" % n, "\t\tU32 a = PARAMLOCAL_U32(GET_OP());\n\t\tU32 b = (U32)GET_OP();\n\t\tPUSH_U32(%s);" % expr))
    for n, _, expr in F32_BIN:
        h.append(handler("JIT_FUSED_F32_%s_LL" % n, "\t\tfloat a = *(float*)(pParamsLocals + GET_OP());\n\t\tfloat b = *(float*)(pParamsLocals + GET_OP());\n\t\tPUSH_FLOAT(%s)" % expr))
        h.append(handler("JIT_FUSED_F32_%s_LC" % n, "\t\tfloat a = *(float*)(pParamsLocals + GET_OP());\n\t\tU32 bits = (U32)GET_OP();\n\t\tfloat b = *(float*)&bits;\n\t\tPUSH_FLOAT(%s)" % expr))
    for n, _, cond in I32_BCC:
        h.append(handler("JIT_FUSED_I32_%s_LL" % n, "\t\tU32 a = PARAMLOCAL_U32(GET_OP());\n\t\tU32 b = PARAMLOCAL_U32(GET_OP());\n\t\tU32 target = (U32)GET_OP();\n\t\tif (%s) {\n\t\t\tpCurOp = pOps + target;\n\t\t}" % cond, branch=True))
        h.append(handler("JIT_FUSED_I32_%s_LC" % n, "\t\tU32 a = PARAMLOCAL_U32(GET_OP());\n\t\tU32 b = (U32)GET_OP();\n\t\tU32 target = (U32)GET_OP();\n\t\tif (%s) {\n\t\t\tpCurOp = pOps + target;\n\t\t}" % cond, branch=True))
    h.append(handler("JIT_FUSED_INC_L", "\t\tU32 ofs = (U32)GET_OP();\n\t\tU32 k = (U32)GET_OP();\n\t\tPARAMLOCAL_U32(ofs) += k;"))
    h.append(handler("JIT_FUSED_LOAD2", "\t\tU32 a = PARAMLOCAL_U32(GET_OP());\n\t\tU32 b = PARAMLOCAL_U32(GET_OP());\n\t\tPUSH_U32(a);\n\t\tPUSH_U32(b);"))
    return "\n".join(h)


def gen_tables():
    t = ["typedef struct { U32 op; U32 ll; U32 lc; int isFloat; } tFusedBin;    // ll is 0 where there is no LL form",
         "static const tFusedBin fusedBins[] = {"]
    for n, op, _ in I32_BIN:
        t.append("\t{ %s, %s, JIT_FUSED_I32_%s_LC, 0 }," % (op, "0" if n in LC_ONLY else "JIT_FUSED_I32_%s_LL" % n, n))
    for n, op, _ in F32_BIN:
        t.append("\t{ %s, JIT_FUSED_F32_%s_LL, JIT_FUSED_F32_%s_LC, 1 }," % (op, n, n))
    t.append("};")
    t.append("typedef struct { U32 op; U32 ll; U32 lc; } tFusedBcc;")
    t.append("static const tFusedBcc fusedBccs[] = {")
    for n, op, _ in I32_BCC:
        t.append("\t{ %s, JIT_FUSED_I32_%s_LL, JIT_FUSED_I32_%s_LC }," % (op, n, n))
    t.append("};")
    # the ops the INC pattern needs to recognise
    t.append("#define FUSED_ADD_OP JIT_ADD_I32I32")
    t.append("#define FUSED_SUB_OP JIT_SUB_I32I32")
    return "\n".join(t)


def gen_main():
    o = ["// GENERATED by tools/gen_fused_ops.py. Do not edit: change the tables there and regenerate.",
         "// Included three times, with FUSED_HANDLERS, FUSED_LABELS or FUSED_TABLES defined: see that script.", "",
         "#if defined(FUSED_HANDLERS)", "", gen_handlers(), "#elif defined(FUSED_LABELS)", ""]
    for name, _ in all_ops():
        o.append("\t\tGET_LABELS(%s);" % name)
    o += ["", "#elif defined(FUSED_TABLES)", "", gen_tables(), "", "#endif", ""]
    return "\n".join(o)


if __name__ == "__main__":
    a, b = gen_ops_header(), gen_main()
    if "--check" in sys.argv:
        if not (os.path.exists(OUT_OPS) and os.path.exists(OUT) and open(OUT_OPS).read() == a and open(OUT).read() == b):
            sys.exit("the fused-instruction headers are out of date: run tools/gen_fused_ops.py")
        print("the fused-instruction headers are up to date")
    else:
        changed = []
        for path, text in ((OUT_OPS, a), (OUT, b)):
            if not (os.path.exists(path) and open(path).read() == text):
                open(path, "w").write(text)
                changed.append(os.path.basename(path))
        print("wrote " + ", ".join(changed) if changed else "unchanged")
